//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalReportingSystem.Core.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Access
    {
        public int ID { get; set; }
        public Nullable<int> AttachedUser { get; set; }
        public Nullable<int> AttachedProject { get; set; }
        public Nullable<int> AttachedGuest { get; set; }
        public bool DeliveryResult { get; set; }
    
        public virtual User User { get; set; }
        public virtual Project Project { get; set; }
        public virtual Guest Guest { get; set; }
    }
}
