//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalReportingSystem.Core.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Analyser
    {
        public int ID { get; set; }
        public int User { get; set; }
        public int TestSet { get; set; }
    
        public virtual TestSuit TestSuit { get; set; }
        public virtual User User1 { get; set; }
    }
}
