//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalReportingSystem.Core.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnalysisHistory
    {
        public int ID { get; set; }
        public Nullable<int> ParentAnalysis { get; set; }
        public Nullable<int> ChangesPerformedBy { get; set; }
        public System.DateTime PerformedAt { get; set; }
        public string PerviousState { get; set; }
        public string NewState { get; set; }
        public string PreviousComments { get; set; }
        public string NewComments { get; set; }
        public Nullable<int> PreviousDefect { get; set; }
        public Nullable<int> NewDefect { get; set; }
    
        public virtual Analysis Analysis { get; set; }
        public virtual User User { get; set; }
        public virtual Defect Defect { get; set; }
        public virtual Defect Defect1 { get; set; }
    }
}
