//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalReportingSystem.Core.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Analysis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Analysis()
        {
            this.AnalysisHistories = new HashSet<AnalysisHistory>();
        }
    
        public int ID { get; set; }
        public Nullable<int> BelongToProject { get; set; }
        public Nullable<int> ParentTestCycle { get; set; }
        public System.DateTime RaisedDate { get; set; }
        public string StepState { get; set; }
        public string Comments { get; set; }
        public string OldDefects { get; set; }
        public Nullable<int> ParentDefect { get; set; }
        public int ParentStep { get; set; }
        public string GlobalPositionTCName { get; set; }
        public int GlobalPositionStepNumber { get; set; }
        public string CurrentDefects { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual TestCycle TestCycle { get; set; }
        public virtual Defect Defect { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnalysisHistory> AnalysisHistories { get; set; }
    }
}
