//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalReportingSystem.Core.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoAnalysisCache
    {
        public int ID { get; set; }
        public int ProjectID { get; set; }
        public string TestSuiteName { get; set; }
        public string TestCaseName { get; set; }
        public string ErrorMessage { get; set; }
        public string DefectID { get; set; }
        public Nullable<System.Guid> Status { get; set; }
        public Nullable<System.DateTime> LastTimeUsed { get; set; }
    }
}
