//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalReportingSystem.Core.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.LoadBalancedMachines = new HashSet<LoadBalancedMachine>();
            this.Scenarios = new HashSet<Scenario>();
            this.TestsExecutions = new HashSet<TestsExecution>();
        }
    
        public int ID { get; set; }
        public string RemoteMachineIP { get; set; }
        public Nullable<int> DefaultAccount { get; set; }
        public int AddedBy { get; set; }
        public System.DateTime AddedDate { get; set; }
        public Nullable<int> BelongToProject { get; set; }
        public string Comments { get; set; }
        public bool AssignedToExecution { get; set; }
        public bool InUse { get; set; }
        public string Firefox { get; set; }
        public string Ie { get; set; }
        public string Chome { get; set; }
        public string windowsversion { get; set; }
        public Nullable<System.Guid> LastGUID { get; set; }
        public string freespace { get; set; }
    
        public virtual AccountForTestRun AccountForTestRun { get; set; }
        public virtual User User { get; set; }
        public virtual Project Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoadBalancedMachine> LoadBalancedMachines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Scenario> Scenarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestsExecution> TestsExecutions { get; set; }
    }
}
