//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalReportingSystem.Core.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Defect
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Defect()
        {
            this.Analyses = new HashSet<Analysis>();
            this.AnalysisHistories = new HashSet<AnalysisHistory>();
            this.AnalysisHistories1 = new HashSet<AnalysisHistory>();
        }
    
        public int ID { get; set; }
        public Nullable<int> BelongToProject { get; set; }
        public Nullable<int> BelongToTracker { get; set; }
        public Nullable<int> AddedBy { get; set; }
        public string DefectID { get; set; }
        public string DefectTitle { get; set; }
        public string DefectComments { get; set; }
        public string DefectState { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Analysis> Analyses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnalysisHistory> AnalysisHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnalysisHistory> AnalysisHistories1 { get; set; }
        public virtual Bugracker Bugracker { get; set; }
        public virtual User User { get; set; }
        public virtual Project Project { get; set; }
    }
}
