//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalReportingSystem.Core.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistributionShedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DistributionShedule()
        {
            this.DistributedTests = new HashSet<DistributedTest>();
        }
    
        public int ID { get; set; }
        public Nullable<int> BelongToProject { get; set; }
        public Nullable<System.Guid> LastSessionID { get; set; }
        public string Machines { get; set; }
        public string Tests { get; set; }
        public Nullable<int> Environment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DistributedTest> DistributedTests { get; set; }
        public virtual Project Project { get; set; }
        public virtual HostsConfiguration HostsConfiguration { get; set; }
    }
}
