//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalReportingSystem.Core.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistributedTest
    {
        public int ID { get; set; }
        public Nullable<int> BelongToShedule { get; set; }
        public string TestName { get; set; }
        public System.Guid BelongToSession { get; set; }
        public Nullable<System.DateTime> StartedAt { get; set; }
        public string Logs { get; set; }
    
        public virtual DistributionShedule DistributionShedule { get; set; }
    }
}
