//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalReportingSystem.Core.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilesStorage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FilesStorage()
        {
            this.NewLoadBalanceds = new HashSet<NewLoadBalanced>();
            this.TestsExecutions = new HashSet<TestsExecution>();
        }
    
        public int ID { get; set; }
        public byte[] FileContent { get; set; }
        public int AddedBy { get; set; }
        public Nullable<int> BelongToProject { get; set; }
        public System.DateTime AddedDate { get; set; }
        public string Comments { get; set; }
        public string Name { get; set; }
    
        public virtual User User { get; set; }
        public virtual Project Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NewLoadBalanced> NewLoadBalanceds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestsExecution> TestsExecutions { get; set; }
    }
}
