//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalReportingSystem.Core.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrpExecutionInfo
    {
        public long ID { get; set; }
        public long GroupID { get; set; }
        public int ProjectId { get; set; }
        public Nullable<int> Client { get; set; }
        public string Tests { get; set; }
        public Nullable<int> Account { get; set; }
        public Nullable<int> ProfileHost { get; set; }
        public string Browser { get; set; }
        public string Comments { get; set; }
        public Nullable<int> FrameworkVersion { get; set; }
        public Nullable<int> Configuration { get; set; }
        public string AccaptanceCriteria { get; set; }
        public string CategoriesInclude { get; set; }
        public string CategoriesExclude { get; set; }
        public Nullable<int> FailsToAlert { get; set; }
        public string Priroty { get; set; }
        public string ExecutionType { get; set; }
        public string Scheduling { get; set; }
        public Nullable<int> TargetTestCycle { get; set; }
        public Nullable<int> LoginPageURL { get; set; }
        public string Subscribers { get; set; }
        public string AddedBy { get; set; }
        public string Status { get; set; }
        public Nullable<bool> isNew { get; set; }

        public virtual ExecutionGroup ExecutionGroup { get; set; }
        public virtual Project Project { get; set; }
    }
}
