//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalReportingSystem.Core.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HostsConfiguration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HostsConfiguration()
        {
            this.DistributionShedules = new HashSet<DistributionShedule>();
            this.LoadBalancedMachines = new HashSet<LoadBalancedMachine>();
            this.Scenarios = new HashSet<Scenario>();
            this.TestsExecutions = new HashSet<TestsExecution>();
        }
    
        public int ID { get; set; }
        public string EnvironmentName { get; set; }
        public Nullable<int> BelongToProject { get; set; }
        public string HostFileContent { get; set; }
        public string ApplicationURL { get; set; }
        public Nullable<bool> isBackDoor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DistributionShedule> DistributionShedules { get; set; }
        public virtual Project Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoadBalancedMachine> LoadBalancedMachines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Scenario> Scenarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestsExecution> TestsExecutions { get; set; }
    }
}
