//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalReportingSystem.Core.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoadBalanced
    {
        public int ID { get; set; }
        public Nullable<int> BelongToProject { get; set; }
        public byte[] SerializableContent { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
