//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalReportingSystem.Core.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoadBalancedMachine
    {
        public int ID { get; set; }
        public Nullable<int> NewLoadBalancedId { get; set; }
        public Nullable<int> MachineId { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<int> EnvironmentId { get; set; }
        public Nullable<int> TargetTestCycle { get; set; }
        public Nullable<int> ExecutionConfigurationId { get; set; }
        public string Browser { get; set; }
        public string Priority { get; set; }
        public string Include { get; set; }
        public string Exclude { get; set; }
    
        public virtual AccountForTestRun AccountForTestRun { get; set; }
        public virtual Client Client { get; set; }
        public virtual ExecutionConfiguration ExecutionConfiguration { get; set; }
        public virtual HostsConfiguration HostsConfiguration { get; set; }
        public virtual NewLoadBalanced NewLoadBalanced { get; set; }
        public virtual TestCycle TestCycle { get; set; }
    }
}
