//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalReportingSystem.Core.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewLoadBalanced
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NewLoadBalanced()
        {
            this.LoadBalancedMachines = new HashSet<LoadBalancedMachine>();
            this.LoadBalancedTests = new HashSet<LoadBalancedTest>();
            this.TestSuits = new HashSet<TestSuit>();
        }
    
        public int ID { get; set; }
        public Nullable<int> BelongToProject { get; set; }
        public Nullable<int> FrameworkId { get; set; }
        public Nullable<System.Guid> RemoteExecutionLink { get; set; }
        public string Comments { get; set; }
        public string Subscribers { get; set; }
    
        public virtual FilesStorage FilesStorage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoadBalancedMachine> LoadBalancedMachines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoadBalancedTest> LoadBalancedTests { get; set; }
        public virtual Project Project { get; set; }
        public virtual NewLoadBalanced NewLoadBalanced1 { get; set; }
        public virtual NewLoadBalanced NewLoadBalanced2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestSuit> TestSuits { get; set; }
    }
}
