//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalReportingSystem.Core.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project()
        {
            this.Accesses = new HashSet<Access>();
            this.AccountForTestRuns = new HashSet<AccountForTestRun>();
            this.Analyses = new HashSet<Analysis>();
            this.Clients = new HashSet<Client>();
            this.Defects = new HashSet<Defect>();
            this.DistributionShedules = new HashSet<DistributionShedule>();
            this.ExecutionConfigurations = new HashSet<ExecutionConfiguration>();
            this.FilesStorages = new HashSet<FilesStorage>();
            this.GrpExecutionInfoes = new HashSet<GrpExecutionInfo>();
            this.HostsConfigurations = new HashSet<HostsConfiguration>();
            this.Issues = new HashSet<Issue>();
            this.LoadBalanceds = new HashSet<LoadBalanced>();
            this.LoginPageMonitors = new HashSet<LoginPageMonitor>();
            this.NewLoadBalanceds = new HashSet<NewLoadBalanced>();
            this.ExecutionGroups = new HashSet<ExecutionGroup>();
            this.QCExportAssignments = new HashSet<QCExportAssignment>();
            this.SikuliObjects = new HashSet<SikuliObject>();
            this.TestCycles = new HashSet<TestCycle>();
            this.TestsExecutions = new HashSet<TestsExecution>();
            this.TestSuits = new HashSet<TestSuit>();
            this.UserSessions = new HashSet<UserSession>();
        }
    
        public int ID { get; set; }
        public string ProjectName { get; set; }
        public string DisplayName { get; set; }
        public string QCLocation { get; set; }
        public string QCServer { get; set; }
        public Nullable<bool> Notification_ResultsDelivery { get; set; }
        public Nullable<int> AssignedBugTracker { get; set; }
        public string CustomStatuses { get; set; }
        public string QcResultsPath { get; set; }
        public string SVNpath { get; set; }
        public string SVNlogin { get; set; }
        public string SVNpassword { get; set; }
        public Nullable<bool> AutoAnalysis { get; set; }
        public string QCTestPlan { get; set; }
        public bool isPublic { get; set; }
        public bool isGUI { get; set; }
        public string GITPath { get; set; }
        public string IsGITDefault { get; set; }
        public string GITUsername { get; set; }
        public string GITPassword { get; set; }
        public Nullable<bool> IsProjectUpdatingOnServer { get; set; }
        public Nullable<int> ProjectUpdatingBy { get; set; }
        public Nullable<bool> IsTestCaseUpdating { get; set; }
        public Nullable<int> TestCaseUpdatedBy { get; set; }
        public Nullable<int> BaseProjectID { get; set; }
        public Nullable<int> ProjectTypeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Access> Accesses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountForTestRun> AccountForTestRuns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Analysis> Analyses { get; set; }
        public virtual Bugracker Bugracker { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client> Clients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Defect> Defects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DistributionShedule> DistributionShedules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExecutionConfiguration> ExecutionConfigurations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FilesStorage> FilesStorages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GrpExecutionInfo> GrpExecutionInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HostsConfiguration> HostsConfigurations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Issue> Issues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoadBalanced> LoadBalanceds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoginPageMonitor> LoginPageMonitors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NewLoadBalanced> NewLoadBalanceds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExecutionGroup> ExecutionGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QCExportAssignment> QCExportAssignments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SikuliObject> SikuliObjects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestCycle> TestCycles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestsExecution> TestsExecutions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestSuit> TestSuits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserSession> UserSessions { get; set; }
    }
}
