//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalReportingSystem.Core.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelExecutionStatu
    {
        public long ID { get; set; }
        public int ExecutionId { get; set; }
        public string MachineIP { get; set; }
        public System.DateTime ExecutionStarted { get; set; }
        public string Comment { get; set; }
        public bool IsExecutionCompleted { get; set; }
        public string CurrentStatus { get; set; }
        public System.DateTime LastStatusCheckedAt { get; set; }
        public System.DateTime CurrentStatusCheckedAt { get; set; }
        public Nullable<long> LastRowCount { get; set; }
        public Nullable<long> LastRowId { get; set; }
        public Nullable<long> NewRowCount { get; set; }
        public Nullable<long> NewRowId { get; set; }
        public string TestSuitIds { get; set; }
        public string ToAddress { get; set; }
    }
}
