//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalReportingSystem.Core.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scenario
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> BelongToClient { get; set; }
        public string FrameworkLocation { get; set; }
        public string Tests { get; set; }
        public Nullable<int> Account { get; set; }
        public Nullable<int> ProfileHost { get; set; }
        public string Browser { get; set; }
        public Nullable<int> Configuration { get; set; }
    
        public virtual AccountForTestRun AccountForTestRun { get; set; }
        public virtual Client Client { get; set; }
        public virtual ExecutionConfiguration ExecutionConfiguration { get; set; }
        public virtual HostsConfiguration HostsConfiguration { get; set; }
    }
}
