//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalReportingSystem.Core.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SikuliObject
    {
        public int ID { get; set; }
        public Nullable<int> parentProject { get; set; }
        public string hash { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<int> addedBy { get; set; }
        public Nullable<int> modifiedBy { get; set; }
        public Nullable<System.DateTime> addedOn { get; set; }
        public Nullable<System.DateTime> modifiedOn { get; set; }
        public byte[] content { get; set; }
        public string isSikuli { get; set; }
        public string contentType { get; set; }
        public string cathegory { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
