//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalReportingSystem.Core.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubStep
    {
        public int ID { get; set; }
        public Nullable<int> ParentStep { get; set; }
        public bool SubStepValid { get; set; }
        public System.DateTime SubStepTime { get; set; }
        public string SubStepMessage { get; set; }
        public string SubStepTechInfo { get; set; }
        public string SubStepScreenShot { get; set; }
        public string SubStepScreenShotDriver { get; set; }
        public Nullable<System.Guid> AnalyzedStatus { get; set; }
        public string Defects { get; set; }
    
        public virtual TestStep TestStep { get; set; }
    }
}
