//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalReportingSystem.Core.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestCycle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TestCycle()
        {
            this.Analyses = new HashSet<Analysis>();
            this.LoadBalancedMachines = new HashSet<LoadBalancedMachine>();
            this.TestsExecutions = new HashSet<TestsExecution>();
            this.TestSuits = new HashSet<TestSuit>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ParentProject { get; set; }
        public string CycleName { get; set; }
        public System.DateTime CycleStart { get; set; }
        public System.DateTime CycleEnd { get; set; }
        public string CycleComments { get; set; }
        public Nullable<bool> CycleIsCurrent { get; set; }
        public Nullable<bool> isInnactive { get; set; }
        public string TeamName { get; set; }
        public string ReleaseName { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Analysis> Analyses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoadBalancedMachine> LoadBalancedMachines { get; set; }
        public virtual Project Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestsExecution> TestsExecutions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestSuit> TestSuits { get; set; }
    }
}
