//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalReportingSystem.Core.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestStep
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TestStep()
        {
            this.SubSteps = new HashSet<SubStep>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ParentTestCase { get; set; }
        public System.DateTime StepStartTime { get; set; }
        public string StepType { get; set; }
        public string StepScreenshot { get; set; }
        public string StepScreenshotDriver { get; set; }
        public string StepExpected { get; set; }
        public string StepDescription { get; set; }
        public string StepActual { get; set; }
        public string StepInputData { get; set; }
        public System.Guid UI { get; set; }
        public string Attachments { get; set; }
        public Nullable<int> SortOrder { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubStep> SubSteps { get; set; }
        public virtual TestCase TestCase { get; set; }
    }
}
