//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalReportingSystem.Core.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestSuit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TestSuit()
        {
            this.Analysers = new HashSet<Analyser>();
            this.TestCases = new HashSet<TestCase>();
            this.TestSuits1 = new HashSet<TestSuit>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ParentProject { get; set; }
        public Nullable<int> ParentClientInfo { get; set; }
        public Nullable<int> ParentTestCycle { get; set; }
        public string TSName { get; set; }
        public System.DateTime TSStart { get; set; }
        public System.Guid UI { get; set; }
        public Nullable<int> PreviousTestSuite { get; set; }
        public Nullable<bool> isAcceptance { get; set; }
        public Nullable<System.Guid> AcceptanceParent { get; set; }
        public Nullable<int> Tester { get; set; }
        public string Comments { get; set; }
        public Nullable<int> FailedTestCases { get; set; }
        public Nullable<int> PassedTestCases { get; set; }
        public Nullable<int> DedicatedLinearExecution { get; set; }
        public Nullable<int> DedicatedLbExecution { get; set; }
        public string Hashtag { get; set; }
        public Nullable<System.DateTime> DeliveryTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Analyser> Analysers { get; set; }
        public virtual ClientsInformation ClientsInformation { get; set; }
        public virtual NewLoadBalanced NewLoadBalanced { get; set; }
        public virtual Project Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestCase> TestCases { get; set; }
        public virtual TestCycle TestCycle { get; set; }
        public virtual TestsExecution TestsExecution { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestSuit> TestSuits1 { get; set; }
        public virtual TestSuit TestSuit1 { get; set; }
        public virtual User User { get; set; }
        public virtual TestSuit TestSuits11 { get; set; }
        public virtual TestSuit TestSuit2 { get; set; }
    }
}
