//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalReportingSystem.Core.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestCase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TestCase()
        {
            this.TestSteps = new HashSet<TestStep>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ParentTestSuite { get; set; }
        public string TCName { get; set; }
        public string TCState { get; set; }
        public System.DateTime TCStartTime { get; set; }
        public System.DateTime TCEndTime { get; set; }
        public string TCAttachments { get; set; }
        public string TCDescription { get; set; }
        public System.Guid UI { get; set; }
        public bool isAnalyzed { get; set; }
        public string Criticality { get; set; }
        public string qc_id { get; set; }
        public string Hashtag { get; set; }
        public Nullable<int> AnalyzedBy { get; set; }
        public Nullable<System.DateTime> AnalyzedDate { get; set; }
    
        public virtual TestSuit TestSuit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestStep> TestSteps { get; set; }
        public virtual User User { get; set; }
    }
}
