//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalReportingSystem.Core.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSession
    {
        public int ID { get; set; }
        public Nullable<int> SessionOwner { get; set; }
        public Nullable<int> LinkedProject { get; set; }
        public System.Guid SessionID { get; set; }
        public System.DateTime SessionStartDate { get; set; }
        public System.DateTime SessionEndDate { get; set; }
        public bool SessionIsEndless { get; set; }
        public string SessionIP { get; set; }
        public string SessionBrowser { get; set; }
        public bool SessionClosed { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual User User { get; set; }
    }
}
