//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalReportingSystem.Core.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_AnalyzedSubSteps
    {
        public int ID { get; set; }
        public string TSName { get; set; }
        public bool isAnalyzed { get; set; }
        public string Defects { get; set; }
        public Nullable<System.Guid> AnalyzedStatus { get; set; }
        public System.DateTime TSStart { get; set; }
        public int TestCaseID { get; set; }
        public string ClientBrowser { get; set; }
    }
}
