//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalReportingSystem.Core.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_FilesStorage
    {
        public int FilesStorage_ID { get; set; }
        public int FilesStorage_AddedBy { get; set; }
        public Nullable<int> FilesStorage_BelongToProject { get; set; }
        public System.DateTime FilesStorage_AddedDate { get; set; }
        public string FilesStorage_Comments { get; set; }
        public string FilesStorage_Name { get; set; }
    }
}
