//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
using QcClient.Tools;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]

public partial class EntityResourceDescriptor : Serializer<EntityResourceDescriptor>
{
    private string tableField;
    
    private string nameField;
    
    private string labelField;
    
    private EntityResourceDescriptorSupportsHistory supportsHistoryField;
    
    private EntityResourceDescriptorSupportsAttachment supportsAttachmentField;
    
    private EntityResourceDescriptorSupportsLock supportsLockField;
    
    private EntityResourceDescriptorSupportsGrouping supportsGroupingField;
    
    private EntityResourceDescriptorSupportsMailing supportsMailingField;
    
    private string supportsMultiValueField;
    
    private string supportsWorkflowField;
    
    private string supportsDataHidingFilterField;
    
    private EntityResourceDescriptorSupportsVC supportsVCField;
    
    private EntityResourceDescriptorSupportsSubtypes supportsSubtypesField;
    
    private EntityResourceDescriptorSupportsCopying supportsCopyingField;
    
    private EntityResourceDescriptorSupportsStorage supportsStorageField;
    
    private string extensionNameField;
    
    private string isSiteEntityField;
    
    private EntityResourceDescriptorAttribute[] attributesField;
    
    private EntityResourceDescriptorIsFirstLevelResource isFirstLevelResourceField;
    
    private string secondLevelResourcesField;
    
    private string collectionNameField;
    
    private string baseUrlField;
    
    /// <remarks/>
    public string Table {
        get {
            return this.tableField;
        }
        set {
            this.tableField = value;
        }
    }
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string Label {
        get {
            return this.labelField;
        }
        set {
            this.labelField = value;
        }
    }
    
    /// <remarks/>
    public EntityResourceDescriptorSupportsHistory SupportsHistory {
        get {
            return this.supportsHistoryField;
        }
        set {
            this.supportsHistoryField = value;
        }
    }
    
    /// <remarks/>
    public EntityResourceDescriptorSupportsAttachment SupportsAttachment {
        get {
            return this.supportsAttachmentField;
        }
        set {
            this.supportsAttachmentField = value;
        }
    }
    
    /// <remarks/>
    public EntityResourceDescriptorSupportsLock SupportsLock {
        get {
            return this.supportsLockField;
        }
        set {
            this.supportsLockField = value;
        }
    }
    
    /// <remarks/>
    public EntityResourceDescriptorSupportsGrouping SupportsGrouping {
        get {
            return this.supportsGroupingField;
        }
        set {
            this.supportsGroupingField = value;
        }
    }
    
    /// <remarks/>
    public EntityResourceDescriptorSupportsMailing SupportsMailing {
        get {
            return this.supportsMailingField;
        }
        set {
            this.supportsMailingField = value;
        }
    }
    
    /// <remarks/>
    public string SupportsMultiValue {
        get {
            return this.supportsMultiValueField;
        }
        set {
            this.supportsMultiValueField = value;
        }
    }
    
    /// <remarks/>
    public string SupportsWorkflow {
        get {
            return this.supportsWorkflowField;
        }
        set {
            this.supportsWorkflowField = value;
        }
    }
    
    /// <remarks/>
    public string SupportsDataHidingFilter {
        get {
            return this.supportsDataHidingFilterField;
        }
        set {
            this.supportsDataHidingFilterField = value;
        }
    }
    
    /// <remarks/>
    public EntityResourceDescriptorSupportsVC SupportsVC {
        get {
            return this.supportsVCField;
        }
        set {
            this.supportsVCField = value;
        }
    }
    
    /// <remarks/>
    public EntityResourceDescriptorSupportsSubtypes SupportsSubtypes {
        get {
            return this.supportsSubtypesField;
        }
        set {
            this.supportsSubtypesField = value;
        }
    }
    
    /// <remarks/>
    public EntityResourceDescriptorSupportsCopying SupportsCopying {
        get {
            return this.supportsCopyingField;
        }
        set {
            this.supportsCopyingField = value;
        }
    }
    
    /// <remarks/>
    public EntityResourceDescriptorSupportsStorage SupportsStorage {
        get {
            return this.supportsStorageField;
        }
        set {
            this.supportsStorageField = value;
        }
    }
    
    /// <remarks/>
    public string ExtensionName {
        get {
            return this.extensionNameField;
        }
        set {
            this.extensionNameField = value;
        }
    }
    
    /// <remarks/>
    public string IsSiteEntity {
        get {
            return this.isSiteEntityField;
        }
        set {
            this.isSiteEntityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Attribute", IsNullable=false)]
    public EntityResourceDescriptorAttribute[] Attributes {
        get {
            return this.attributesField;
        }
        set {
            this.attributesField = value;
        }
    }
    
    /// <remarks/>
    public EntityResourceDescriptorIsFirstLevelResource IsFirstLevelResource {
        get {
            return this.isFirstLevelResourceField;
        }
        set {
            this.isFirstLevelResourceField = value;
        }
    }
    
    /// <remarks/>
    public string SecondLevelResources {
        get {
            return this.secondLevelResourcesField;
        }
        set {
            this.secondLevelResourcesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string collectionName {
        get {
            return this.collectionNameField;
        }
        set {
            this.collectionNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string baseUrl {
        get {
            return this.baseUrlField;
        }
        set {
            this.baseUrlField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class EntityResourceDescriptorSupportsHistory {
    
    private string urlField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string url {
        get {
            return this.urlField;
        }
        set {
            this.urlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class EntityResourceDescriptorSupportsAttachment {
    
    private string urlField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string url {
        get {
            return this.urlField;
        }
        set {
            this.urlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class EntityResourceDescriptorSupportsLock {
    
    private string urlField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string url {
        get {
            return this.urlField;
        }
        set {
            this.urlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class EntityResourceDescriptorSupportsGrouping {
    
    private string urlField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string url {
        get {
            return this.urlField;
        }
        set {
            this.urlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class EntityResourceDescriptorSupportsMailing {
    
    private string urlField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string url {
        get {
            return this.urlField;
        }
        set {
            this.urlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class EntityResourceDescriptorSupportsVC {
    
    private string urlField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string url {
        get {
            return this.urlField;
        }
        set {
            this.urlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class EntityResourceDescriptorSupportsSubtypes {
    
    private string subTypeFieldNameField;
    
    private string urlField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string subTypeFieldName {
        get {
            return this.subTypeFieldNameField;
        }
        set {
            this.subTypeFieldNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string url {
        get {
            return this.urlField;
        }
        set {
            this.urlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class EntityResourceDescriptorSupportsCopying {
    
    private string urlField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string url {
        get {
            return this.urlField;
        }
        set {
            this.urlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class EntityResourceDescriptorSupportsStorage {
    
    private string urlField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string url {
        get {
            return this.urlField;
        }
        set {
            this.urlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class EntityResourceDescriptorAttribute {
    
    private string nameField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class EntityResourceDescriptorIsFirstLevelResource {
    
    private string supportsDELETEField;
    
    private string supportsPUTField;
    
    private string supportsGETField;
    
    private string supportsPOSTField;
    
    private string urlField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string supportsDELETE {
        get {
            return this.supportsDELETEField;
        }
        set {
            this.supportsDELETEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string supportsPUT {
        get {
            return this.supportsPUTField;
        }
        set {
            this.supportsPUTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string supportsGET {
        get {
            return this.supportsGETField;
        }
        set {
            this.supportsGETField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string supportsPOST {
        get {
            return this.supportsPOSTField;
        }
        set {
            this.supportsPOSTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string url {
        get {
            return this.urlField;
        }
        set {
            this.urlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}
