//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalReportingSystem.Web.UI.AnalysisService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://microsoft.com/webservices/", ItemName="int")]
    [System.SerializableAttribute()]
    public class ArrayOfInt : System.Collections.Generic.List<int> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://microsoft.com/webservices/", ConfigurationName="AnalysisService.AnalysisServiceSoap")]
    public interface AnalysisServiceSoap {
        
        // CODEGEN: Generating message contract since element name testSuiteIds from namespace http://microsoft.com/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/PerformAutoMigration", ReplyAction="*")]
        GlobalReportingSystem.Web.UI.AnalysisService.PerformAutoMigrationResponse PerformAutoMigration(GlobalReportingSystem.Web.UI.AnalysisService.PerformAutoMigrationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/PerformAutoMigration", ReplyAction="*")]
        System.Threading.Tasks.Task<GlobalReportingSystem.Web.UI.AnalysisService.PerformAutoMigrationResponse> PerformAutoMigrationAsync(GlobalReportingSystem.Web.UI.AnalysisService.PerformAutoMigrationRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PerformAutoMigrationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PerformAutoMigration", Namespace="http://microsoft.com/webservices/", Order=0)]
        public GlobalReportingSystem.Web.UI.AnalysisService.PerformAutoMigrationRequestBody Body;
        
        public PerformAutoMigrationRequest() {
        }
        
        public PerformAutoMigrationRequest(GlobalReportingSystem.Web.UI.AnalysisService.PerformAutoMigrationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class PerformAutoMigrationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public GlobalReportingSystem.Web.UI.AnalysisService.ArrayOfInt testSuiteIds;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int migrationType;
        
        public PerformAutoMigrationRequestBody() {
        }
        
        public PerformAutoMigrationRequestBody(GlobalReportingSystem.Web.UI.AnalysisService.ArrayOfInt testSuiteIds, int migrationType) {
            this.testSuiteIds = testSuiteIds;
            this.migrationType = migrationType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PerformAutoMigrationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PerformAutoMigrationResponse", Namespace="http://microsoft.com/webservices/", Order=0)]
        public GlobalReportingSystem.Web.UI.AnalysisService.PerformAutoMigrationResponseBody Body;
        
        public PerformAutoMigrationResponse() {
        }
        
        public PerformAutoMigrationResponse(GlobalReportingSystem.Web.UI.AnalysisService.PerformAutoMigrationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class PerformAutoMigrationResponseBody {
        
        public PerformAutoMigrationResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AnalysisServiceSoapChannel : GlobalReportingSystem.Web.UI.AnalysisService.AnalysisServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AnalysisServiceSoapClient : System.ServiceModel.ClientBase<GlobalReportingSystem.Web.UI.AnalysisService.AnalysisServiceSoap>, GlobalReportingSystem.Web.UI.AnalysisService.AnalysisServiceSoap {
        
        public AnalysisServiceSoapClient() {
        }
        
        public AnalysisServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AnalysisServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AnalysisServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AnalysisServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GlobalReportingSystem.Web.UI.AnalysisService.PerformAutoMigrationResponse GlobalReportingSystem.Web.UI.AnalysisService.AnalysisServiceSoap.PerformAutoMigration(GlobalReportingSystem.Web.UI.AnalysisService.PerformAutoMigrationRequest request) {
            return base.Channel.PerformAutoMigration(request);
        }
        
        public void PerformAutoMigration(GlobalReportingSystem.Web.UI.AnalysisService.ArrayOfInt testSuiteIds, int migrationType) {
            GlobalReportingSystem.Web.UI.AnalysisService.PerformAutoMigrationRequest inValue = new GlobalReportingSystem.Web.UI.AnalysisService.PerformAutoMigrationRequest();
            inValue.Body = new GlobalReportingSystem.Web.UI.AnalysisService.PerformAutoMigrationRequestBody();
            inValue.Body.testSuiteIds = testSuiteIds;
            inValue.Body.migrationType = migrationType;
            GlobalReportingSystem.Web.UI.AnalysisService.PerformAutoMigrationResponse retVal = ((GlobalReportingSystem.Web.UI.AnalysisService.AnalysisServiceSoap)(this)).PerformAutoMigration(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GlobalReportingSystem.Web.UI.AnalysisService.PerformAutoMigrationResponse> GlobalReportingSystem.Web.UI.AnalysisService.AnalysisServiceSoap.PerformAutoMigrationAsync(GlobalReportingSystem.Web.UI.AnalysisService.PerformAutoMigrationRequest request) {
            return base.Channel.PerformAutoMigrationAsync(request);
        }
        
        public System.Threading.Tasks.Task<GlobalReportingSystem.Web.UI.AnalysisService.PerformAutoMigrationResponse> PerformAutoMigrationAsync(GlobalReportingSystem.Web.UI.AnalysisService.ArrayOfInt testSuiteIds, int migrationType) {
            GlobalReportingSystem.Web.UI.AnalysisService.PerformAutoMigrationRequest inValue = new GlobalReportingSystem.Web.UI.AnalysisService.PerformAutoMigrationRequest();
            inValue.Body = new GlobalReportingSystem.Web.UI.AnalysisService.PerformAutoMigrationRequestBody();
            inValue.Body.testSuiteIds = testSuiteIds;
            inValue.Body.migrationType = migrationType;
            return ((GlobalReportingSystem.Web.UI.AnalysisService.AnalysisServiceSoap)(this)).PerformAutoMigrationAsync(inValue);
        }
    }
}
