//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalReportingSystem.Web.UI.SikuliService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SikuliItem", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class SikuliItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProjectNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ProjectName {
            get {
                return this.ProjectNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectNameField, value) != true)) {
                    this.ProjectNameField = value;
                    this.RaisePropertyChanged("ProjectName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SikuliService.SikuliServiceSoap")]
    public interface SikuliServiceSoap {
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateSikuliItem", ReplyAction="*")]
        GlobalReportingSystem.Web.UI.SikuliService.UpdateSikuliItemResponse UpdateSikuliItem(GlobalReportingSystem.Web.UI.SikuliService.UpdateSikuliItemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateSikuliItem", ReplyAction="*")]
        System.Threading.Tasks.Task<GlobalReportingSystem.Web.UI.SikuliService.UpdateSikuliItemResponse> UpdateSikuliItemAsync(GlobalReportingSystem.Web.UI.SikuliService.UpdateSikuliItemRequest request);
        
        // CODEGEN: Generating message contract since element name GetSikuliItemResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSikuliItem", ReplyAction="*")]
        GlobalReportingSystem.Web.UI.SikuliService.GetSikuliItemResponse GetSikuliItem(GlobalReportingSystem.Web.UI.SikuliService.GetSikuliItemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSikuliItem", ReplyAction="*")]
        System.Threading.Tasks.Task<GlobalReportingSystem.Web.UI.SikuliService.GetSikuliItemResponse> GetSikuliItemAsync(GlobalReportingSystem.Web.UI.SikuliService.GetSikuliItemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveSikuliItem", ReplyAction="*")]
        void RemoveSikuliItem(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveSikuliItem", ReplyAction="*")]
        System.Threading.Tasks.Task RemoveSikuliItemAsync(int id);
        
        // CODEGEN: Generating message contract since element name content from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddSikuliItem", ReplyAction="*")]
        GlobalReportingSystem.Web.UI.SikuliService.AddSikuliItemResponse AddSikuliItem(GlobalReportingSystem.Web.UI.SikuliService.AddSikuliItemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddSikuliItem", ReplyAction="*")]
        System.Threading.Tasks.Task<GlobalReportingSystem.Web.UI.SikuliService.AddSikuliItemResponse> AddSikuliItemAsync(GlobalReportingSystem.Web.UI.SikuliService.AddSikuliItemRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateSikuliItemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateSikuliItem", Namespace="http://tempuri.org/", Order=0)]
        public GlobalReportingSystem.Web.UI.SikuliService.UpdateSikuliItemRequestBody Body;
        
        public UpdateSikuliItemRequest() {
        }
        
        public UpdateSikuliItemRequest(GlobalReportingSystem.Web.UI.SikuliService.UpdateSikuliItemRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateSikuliItemRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int sessionId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string description;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string cathegory;
        
        public UpdateSikuliItemRequestBody() {
        }
        
        public UpdateSikuliItemRequestBody(int id, int sessionId, string name, string description, string cathegory) {
            this.id = id;
            this.sessionId = sessionId;
            this.name = name;
            this.description = description;
            this.cathegory = cathegory;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateSikuliItemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateSikuliItemResponse", Namespace="http://tempuri.org/", Order=0)]
        public GlobalReportingSystem.Web.UI.SikuliService.UpdateSikuliItemResponseBody Body;
        
        public UpdateSikuliItemResponse() {
        }
        
        public UpdateSikuliItemResponse(GlobalReportingSystem.Web.UI.SikuliService.UpdateSikuliItemResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateSikuliItemResponseBody {
        
        public UpdateSikuliItemResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSikuliItemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSikuliItem", Namespace="http://tempuri.org/", Order=0)]
        public GlobalReportingSystem.Web.UI.SikuliService.GetSikuliItemRequestBody Body;
        
        public GetSikuliItemRequest() {
        }
        
        public GetSikuliItemRequest(GlobalReportingSystem.Web.UI.SikuliService.GetSikuliItemRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSikuliItemRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetSikuliItemRequestBody() {
        }
        
        public GetSikuliItemRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSikuliItemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSikuliItemResponse", Namespace="http://tempuri.org/", Order=0)]
        public GlobalReportingSystem.Web.UI.SikuliService.GetSikuliItemResponseBody Body;
        
        public GetSikuliItemResponse() {
        }
        
        public GetSikuliItemResponse(GlobalReportingSystem.Web.UI.SikuliService.GetSikuliItemResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSikuliItemResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public GlobalReportingSystem.Web.UI.SikuliService.SikuliItem GetSikuliItemResult;
        
        public GetSikuliItemResponseBody() {
        }
        
        public GetSikuliItemResponseBody(GlobalReportingSystem.Web.UI.SikuliService.SikuliItem GetSikuliItemResult) {
            this.GetSikuliItemResult = GetSikuliItemResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddSikuliItemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddSikuliItem", Namespace="http://tempuri.org/", Order=0)]
        public GlobalReportingSystem.Web.UI.SikuliService.AddSikuliItemRequestBody Body;
        
        public AddSikuliItemRequest() {
        }
        
        public AddSikuliItemRequest(GlobalReportingSystem.Web.UI.SikuliService.AddSikuliItemRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddSikuliItemRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] content;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int sessionId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string fileName;
        
        public AddSikuliItemRequestBody() {
        }
        
        public AddSikuliItemRequestBody(byte[] content, int sessionId, string fileName) {
            this.content = content;
            this.sessionId = sessionId;
            this.fileName = fileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddSikuliItemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddSikuliItemResponse", Namespace="http://tempuri.org/", Order=0)]
        public GlobalReportingSystem.Web.UI.SikuliService.AddSikuliItemResponseBody Body;
        
        public AddSikuliItemResponse() {
        }
        
        public AddSikuliItemResponse(GlobalReportingSystem.Web.UI.SikuliService.AddSikuliItemResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddSikuliItemResponseBody {
        
        public AddSikuliItemResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SikuliServiceSoapChannel : GlobalReportingSystem.Web.UI.SikuliService.SikuliServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SikuliServiceSoapClient : System.ServiceModel.ClientBase<GlobalReportingSystem.Web.UI.SikuliService.SikuliServiceSoap>, GlobalReportingSystem.Web.UI.SikuliService.SikuliServiceSoap {
        
        public SikuliServiceSoapClient() {
        }
        
        public SikuliServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SikuliServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SikuliServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SikuliServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GlobalReportingSystem.Web.UI.SikuliService.UpdateSikuliItemResponse GlobalReportingSystem.Web.UI.SikuliService.SikuliServiceSoap.UpdateSikuliItem(GlobalReportingSystem.Web.UI.SikuliService.UpdateSikuliItemRequest request) {
            return base.Channel.UpdateSikuliItem(request);
        }
        
        public void UpdateSikuliItem(int id, int sessionId, string name, string description, string cathegory) {
            GlobalReportingSystem.Web.UI.SikuliService.UpdateSikuliItemRequest inValue = new GlobalReportingSystem.Web.UI.SikuliService.UpdateSikuliItemRequest();
            inValue.Body = new GlobalReportingSystem.Web.UI.SikuliService.UpdateSikuliItemRequestBody();
            inValue.Body.id = id;
            inValue.Body.sessionId = sessionId;
            inValue.Body.name = name;
            inValue.Body.description = description;
            inValue.Body.cathegory = cathegory;
            GlobalReportingSystem.Web.UI.SikuliService.UpdateSikuliItemResponse retVal = ((GlobalReportingSystem.Web.UI.SikuliService.SikuliServiceSoap)(this)).UpdateSikuliItem(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GlobalReportingSystem.Web.UI.SikuliService.UpdateSikuliItemResponse> GlobalReportingSystem.Web.UI.SikuliService.SikuliServiceSoap.UpdateSikuliItemAsync(GlobalReportingSystem.Web.UI.SikuliService.UpdateSikuliItemRequest request) {
            return base.Channel.UpdateSikuliItemAsync(request);
        }
        
        public System.Threading.Tasks.Task<GlobalReportingSystem.Web.UI.SikuliService.UpdateSikuliItemResponse> UpdateSikuliItemAsync(int id, int sessionId, string name, string description, string cathegory) {
            GlobalReportingSystem.Web.UI.SikuliService.UpdateSikuliItemRequest inValue = new GlobalReportingSystem.Web.UI.SikuliService.UpdateSikuliItemRequest();
            inValue.Body = new GlobalReportingSystem.Web.UI.SikuliService.UpdateSikuliItemRequestBody();
            inValue.Body.id = id;
            inValue.Body.sessionId = sessionId;
            inValue.Body.name = name;
            inValue.Body.description = description;
            inValue.Body.cathegory = cathegory;
            return ((GlobalReportingSystem.Web.UI.SikuliService.SikuliServiceSoap)(this)).UpdateSikuliItemAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GlobalReportingSystem.Web.UI.SikuliService.GetSikuliItemResponse GlobalReportingSystem.Web.UI.SikuliService.SikuliServiceSoap.GetSikuliItem(GlobalReportingSystem.Web.UI.SikuliService.GetSikuliItemRequest request) {
            return base.Channel.GetSikuliItem(request);
        }
        
        public GlobalReportingSystem.Web.UI.SikuliService.SikuliItem GetSikuliItem(int id) {
            GlobalReportingSystem.Web.UI.SikuliService.GetSikuliItemRequest inValue = new GlobalReportingSystem.Web.UI.SikuliService.GetSikuliItemRequest();
            inValue.Body = new GlobalReportingSystem.Web.UI.SikuliService.GetSikuliItemRequestBody();
            inValue.Body.id = id;
            GlobalReportingSystem.Web.UI.SikuliService.GetSikuliItemResponse retVal = ((GlobalReportingSystem.Web.UI.SikuliService.SikuliServiceSoap)(this)).GetSikuliItem(inValue);
            return retVal.Body.GetSikuliItemResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GlobalReportingSystem.Web.UI.SikuliService.GetSikuliItemResponse> GlobalReportingSystem.Web.UI.SikuliService.SikuliServiceSoap.GetSikuliItemAsync(GlobalReportingSystem.Web.UI.SikuliService.GetSikuliItemRequest request) {
            return base.Channel.GetSikuliItemAsync(request);
        }
        
        public System.Threading.Tasks.Task<GlobalReportingSystem.Web.UI.SikuliService.GetSikuliItemResponse> GetSikuliItemAsync(int id) {
            GlobalReportingSystem.Web.UI.SikuliService.GetSikuliItemRequest inValue = new GlobalReportingSystem.Web.UI.SikuliService.GetSikuliItemRequest();
            inValue.Body = new GlobalReportingSystem.Web.UI.SikuliService.GetSikuliItemRequestBody();
            inValue.Body.id = id;
            return ((GlobalReportingSystem.Web.UI.SikuliService.SikuliServiceSoap)(this)).GetSikuliItemAsync(inValue);
        }
        
        public void RemoveSikuliItem(int id) {
            base.Channel.RemoveSikuliItem(id);
        }
        
        public System.Threading.Tasks.Task RemoveSikuliItemAsync(int id) {
            return base.Channel.RemoveSikuliItemAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GlobalReportingSystem.Web.UI.SikuliService.AddSikuliItemResponse GlobalReportingSystem.Web.UI.SikuliService.SikuliServiceSoap.AddSikuliItem(GlobalReportingSystem.Web.UI.SikuliService.AddSikuliItemRequest request) {
            return base.Channel.AddSikuliItem(request);
        }
        
        public void AddSikuliItem(byte[] content, int sessionId, string fileName) {
            GlobalReportingSystem.Web.UI.SikuliService.AddSikuliItemRequest inValue = new GlobalReportingSystem.Web.UI.SikuliService.AddSikuliItemRequest();
            inValue.Body = new GlobalReportingSystem.Web.UI.SikuliService.AddSikuliItemRequestBody();
            inValue.Body.content = content;
            inValue.Body.sessionId = sessionId;
            inValue.Body.fileName = fileName;
            GlobalReportingSystem.Web.UI.SikuliService.AddSikuliItemResponse retVal = ((GlobalReportingSystem.Web.UI.SikuliService.SikuliServiceSoap)(this)).AddSikuliItem(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GlobalReportingSystem.Web.UI.SikuliService.AddSikuliItemResponse> GlobalReportingSystem.Web.UI.SikuliService.SikuliServiceSoap.AddSikuliItemAsync(GlobalReportingSystem.Web.UI.SikuliService.AddSikuliItemRequest request) {
            return base.Channel.AddSikuliItemAsync(request);
        }
        
        public System.Threading.Tasks.Task<GlobalReportingSystem.Web.UI.SikuliService.AddSikuliItemResponse> AddSikuliItemAsync(byte[] content, int sessionId, string fileName) {
            GlobalReportingSystem.Web.UI.SikuliService.AddSikuliItemRequest inValue = new GlobalReportingSystem.Web.UI.SikuliService.AddSikuliItemRequest();
            inValue.Body = new GlobalReportingSystem.Web.UI.SikuliService.AddSikuliItemRequestBody();
            inValue.Body.content = content;
            inValue.Body.sessionId = sessionId;
            inValue.Body.fileName = fileName;
            return ((GlobalReportingSystem.Web.UI.SikuliService.SikuliServiceSoap)(this)).AddSikuliItemAsync(inValue);
        }
    }
}
