//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalReportingSystem.Web.UI.Harvest {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://GRSUri.com/", ConfigurationName="Harvest.ServiceConnectorSoap")]
    public interface ServiceConnectorSoap {
        
        // CODEGEN: Generating message contract since element name ZipFile from namespace http://GRSUri.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://GRSUri.com/AcceptReport", ReplyAction="*")]
        GlobalReportingSystem.Web.UI.Harvest.AcceptReportResponse AcceptReport(GlobalReportingSystem.Web.UI.Harvest.AcceptReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://GRSUri.com/AcceptReport", ReplyAction="*")]
        System.Threading.Tasks.Task<GlobalReportingSystem.Web.UI.Harvest.AcceptReportResponse> AcceptReportAsync(GlobalReportingSystem.Web.UI.Harvest.AcceptReportRequest request);
        
        // CODEGEN: Generating message contract since element name AcceptReportTestResult from namespace http://GRSUri.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://GRSUri.com/AcceptReportTest", ReplyAction="*")]
        GlobalReportingSystem.Web.UI.Harvest.AcceptReportTestResponse AcceptReportTest(GlobalReportingSystem.Web.UI.Harvest.AcceptReportTestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://GRSUri.com/AcceptReportTest", ReplyAction="*")]
        System.Threading.Tasks.Task<GlobalReportingSystem.Web.UI.Harvest.AcceptReportTestResponse> AcceptReportTestAsync(GlobalReportingSystem.Web.UI.Harvest.AcceptReportTestRequest request);
        
        // CODEGEN: Generating message contract since element name ProjectName from namespace http://GRSUri.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://GRSUri.com/currentCycle", ReplyAction="*")]
        GlobalReportingSystem.Web.UI.Harvest.currentCycleResponse currentCycle(GlobalReportingSystem.Web.UI.Harvest.currentCycleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://GRSUri.com/currentCycle", ReplyAction="*")]
        System.Threading.Tasks.Task<GlobalReportingSystem.Web.UI.Harvest.currentCycleResponse> currentCycleAsync(GlobalReportingSystem.Web.UI.Harvest.currentCycleRequest request);
        
        // CODEGEN: Generating message contract since element name ProjectName from namespace http://GRSUri.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://GRSUri.com/isProjectExists", ReplyAction="*")]
        GlobalReportingSystem.Web.UI.Harvest.isProjectExistsResponse isProjectExists(GlobalReportingSystem.Web.UI.Harvest.isProjectExistsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://GRSUri.com/isProjectExists", ReplyAction="*")]
        System.Threading.Tasks.Task<GlobalReportingSystem.Web.UI.Harvest.isProjectExistsResponse> isProjectExistsAsync(GlobalReportingSystem.Web.UI.Harvest.isProjectExistsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AcceptReportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AcceptReport", Namespace="http://GRSUri.com/", Order=0)]
        public GlobalReportingSystem.Web.UI.Harvest.AcceptReportRequestBody Body;
        
        public AcceptReportRequest() {
        }
        
        public AcceptReportRequest(GlobalReportingSystem.Web.UI.Harvest.AcceptReportRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://GRSUri.com/")]
    public partial class AcceptReportRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] ZipFile;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.Nullable<int> taskId;
        
        public AcceptReportRequestBody() {
        }
        
        public AcceptReportRequestBody(byte[] ZipFile, System.Nullable<int> taskId) {
            this.ZipFile = ZipFile;
            this.taskId = taskId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AcceptReportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AcceptReportResponse", Namespace="http://GRSUri.com/", Order=0)]
        public GlobalReportingSystem.Web.UI.Harvest.AcceptReportResponseBody Body;
        
        public AcceptReportResponse() {
        }
        
        public AcceptReportResponse(GlobalReportingSystem.Web.UI.Harvest.AcceptReportResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://GRSUri.com/")]
    public partial class AcceptReportResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AcceptReportResult;
        
        public AcceptReportResponseBody() {
        }
        
        public AcceptReportResponseBody(string AcceptReportResult) {
            this.AcceptReportResult = AcceptReportResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AcceptReportTestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AcceptReportTest", Namespace="http://GRSUri.com/", Order=0)]
        public GlobalReportingSystem.Web.UI.Harvest.AcceptReportTestRequestBody Body;
        
        public AcceptReportTestRequest() {
        }
        
        public AcceptReportTestRequest(GlobalReportingSystem.Web.UI.Harvest.AcceptReportTestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AcceptReportTestRequestBody {
        
        public AcceptReportTestRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AcceptReportTestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AcceptReportTestResponse", Namespace="http://GRSUri.com/", Order=0)]
        public GlobalReportingSystem.Web.UI.Harvest.AcceptReportTestResponseBody Body;
        
        public AcceptReportTestResponse() {
        }
        
        public AcceptReportTestResponse(GlobalReportingSystem.Web.UI.Harvest.AcceptReportTestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://GRSUri.com/")]
    public partial class AcceptReportTestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AcceptReportTestResult;
        
        public AcceptReportTestResponseBody() {
        }
        
        public AcceptReportTestResponseBody(string AcceptReportTestResult) {
            this.AcceptReportTestResult = AcceptReportTestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class currentCycleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="currentCycle", Namespace="http://GRSUri.com/", Order=0)]
        public GlobalReportingSystem.Web.UI.Harvest.currentCycleRequestBody Body;
        
        public currentCycleRequest() {
        }
        
        public currentCycleRequest(GlobalReportingSystem.Web.UI.Harvest.currentCycleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://GRSUri.com/")]
    public partial class currentCycleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ProjectName;
        
        public currentCycleRequestBody() {
        }
        
        public currentCycleRequestBody(string ProjectName) {
            this.ProjectName = ProjectName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class currentCycleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="currentCycleResponse", Namespace="http://GRSUri.com/", Order=0)]
        public GlobalReportingSystem.Web.UI.Harvest.currentCycleResponseBody Body;
        
        public currentCycleResponse() {
        }
        
        public currentCycleResponse(GlobalReportingSystem.Web.UI.Harvest.currentCycleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://GRSUri.com/")]
    public partial class currentCycleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string currentCycleResult;
        
        public currentCycleResponseBody() {
        }
        
        public currentCycleResponseBody(string currentCycleResult) {
            this.currentCycleResult = currentCycleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isProjectExistsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isProjectExists", Namespace="http://GRSUri.com/", Order=0)]
        public GlobalReportingSystem.Web.UI.Harvest.isProjectExistsRequestBody Body;
        
        public isProjectExistsRequest() {
        }
        
        public isProjectExistsRequest(GlobalReportingSystem.Web.UI.Harvest.isProjectExistsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://GRSUri.com/")]
    public partial class isProjectExistsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ProjectName;
        
        public isProjectExistsRequestBody() {
        }
        
        public isProjectExistsRequestBody(string ProjectName) {
            this.ProjectName = ProjectName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isProjectExistsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isProjectExistsResponse", Namespace="http://GRSUri.com/", Order=0)]
        public GlobalReportingSystem.Web.UI.Harvest.isProjectExistsResponseBody Body;
        
        public isProjectExistsResponse() {
        }
        
        public isProjectExistsResponse(GlobalReportingSystem.Web.UI.Harvest.isProjectExistsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://GRSUri.com/")]
    public partial class isProjectExistsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool isProjectExistsResult;
        
        public isProjectExistsResponseBody() {
        }
        
        public isProjectExistsResponseBody(bool isProjectExistsResult) {
            this.isProjectExistsResult = isProjectExistsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceConnectorSoapChannel : GlobalReportingSystem.Web.UI.Harvest.ServiceConnectorSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceConnectorSoapClient : System.ServiceModel.ClientBase<GlobalReportingSystem.Web.UI.Harvest.ServiceConnectorSoap>, GlobalReportingSystem.Web.UI.Harvest.ServiceConnectorSoap {
        
        public ServiceConnectorSoapClient() {
        }
        
        public ServiceConnectorSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceConnectorSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceConnectorSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceConnectorSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GlobalReportingSystem.Web.UI.Harvest.AcceptReportResponse GlobalReportingSystem.Web.UI.Harvest.ServiceConnectorSoap.AcceptReport(GlobalReportingSystem.Web.UI.Harvest.AcceptReportRequest request) {
            return base.Channel.AcceptReport(request);
        }
        
        public string AcceptReport(byte[] ZipFile, System.Nullable<int> taskId) {
            GlobalReportingSystem.Web.UI.Harvest.AcceptReportRequest inValue = new GlobalReportingSystem.Web.UI.Harvest.AcceptReportRequest();
            inValue.Body = new GlobalReportingSystem.Web.UI.Harvest.AcceptReportRequestBody();
            inValue.Body.ZipFile = ZipFile;
            inValue.Body.taskId = taskId;
            GlobalReportingSystem.Web.UI.Harvest.AcceptReportResponse retVal = ((GlobalReportingSystem.Web.UI.Harvest.ServiceConnectorSoap)(this)).AcceptReport(inValue);
            return retVal.Body.AcceptReportResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GlobalReportingSystem.Web.UI.Harvest.AcceptReportResponse> GlobalReportingSystem.Web.UI.Harvest.ServiceConnectorSoap.AcceptReportAsync(GlobalReportingSystem.Web.UI.Harvest.AcceptReportRequest request) {
            return base.Channel.AcceptReportAsync(request);
        }
        
        public System.Threading.Tasks.Task<GlobalReportingSystem.Web.UI.Harvest.AcceptReportResponse> AcceptReportAsync(byte[] ZipFile, System.Nullable<int> taskId) {
            GlobalReportingSystem.Web.UI.Harvest.AcceptReportRequest inValue = new GlobalReportingSystem.Web.UI.Harvest.AcceptReportRequest();
            inValue.Body = new GlobalReportingSystem.Web.UI.Harvest.AcceptReportRequestBody();
            inValue.Body.ZipFile = ZipFile;
            inValue.Body.taskId = taskId;
            return ((GlobalReportingSystem.Web.UI.Harvest.ServiceConnectorSoap)(this)).AcceptReportAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GlobalReportingSystem.Web.UI.Harvest.AcceptReportTestResponse GlobalReportingSystem.Web.UI.Harvest.ServiceConnectorSoap.AcceptReportTest(GlobalReportingSystem.Web.UI.Harvest.AcceptReportTestRequest request) {
            return base.Channel.AcceptReportTest(request);
        }
        
        public string AcceptReportTest() {
            GlobalReportingSystem.Web.UI.Harvest.AcceptReportTestRequest inValue = new GlobalReportingSystem.Web.UI.Harvest.AcceptReportTestRequest();
            inValue.Body = new GlobalReportingSystem.Web.UI.Harvest.AcceptReportTestRequestBody();
            GlobalReportingSystem.Web.UI.Harvest.AcceptReportTestResponse retVal = ((GlobalReportingSystem.Web.UI.Harvest.ServiceConnectorSoap)(this)).AcceptReportTest(inValue);
            return retVal.Body.AcceptReportTestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GlobalReportingSystem.Web.UI.Harvest.AcceptReportTestResponse> GlobalReportingSystem.Web.UI.Harvest.ServiceConnectorSoap.AcceptReportTestAsync(GlobalReportingSystem.Web.UI.Harvest.AcceptReportTestRequest request) {
            return base.Channel.AcceptReportTestAsync(request);
        }
        
        public System.Threading.Tasks.Task<GlobalReportingSystem.Web.UI.Harvest.AcceptReportTestResponse> AcceptReportTestAsync() {
            GlobalReportingSystem.Web.UI.Harvest.AcceptReportTestRequest inValue = new GlobalReportingSystem.Web.UI.Harvest.AcceptReportTestRequest();
            inValue.Body = new GlobalReportingSystem.Web.UI.Harvest.AcceptReportTestRequestBody();
            return ((GlobalReportingSystem.Web.UI.Harvest.ServiceConnectorSoap)(this)).AcceptReportTestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GlobalReportingSystem.Web.UI.Harvest.currentCycleResponse GlobalReportingSystem.Web.UI.Harvest.ServiceConnectorSoap.currentCycle(GlobalReportingSystem.Web.UI.Harvest.currentCycleRequest request) {
            return base.Channel.currentCycle(request);
        }
        
        public string currentCycle(string ProjectName) {
            GlobalReportingSystem.Web.UI.Harvest.currentCycleRequest inValue = new GlobalReportingSystem.Web.UI.Harvest.currentCycleRequest();
            inValue.Body = new GlobalReportingSystem.Web.UI.Harvest.currentCycleRequestBody();
            inValue.Body.ProjectName = ProjectName;
            GlobalReportingSystem.Web.UI.Harvest.currentCycleResponse retVal = ((GlobalReportingSystem.Web.UI.Harvest.ServiceConnectorSoap)(this)).currentCycle(inValue);
            return retVal.Body.currentCycleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GlobalReportingSystem.Web.UI.Harvest.currentCycleResponse> GlobalReportingSystem.Web.UI.Harvest.ServiceConnectorSoap.currentCycleAsync(GlobalReportingSystem.Web.UI.Harvest.currentCycleRequest request) {
            return base.Channel.currentCycleAsync(request);
        }
        
        public System.Threading.Tasks.Task<GlobalReportingSystem.Web.UI.Harvest.currentCycleResponse> currentCycleAsync(string ProjectName) {
            GlobalReportingSystem.Web.UI.Harvest.currentCycleRequest inValue = new GlobalReportingSystem.Web.UI.Harvest.currentCycleRequest();
            inValue.Body = new GlobalReportingSystem.Web.UI.Harvest.currentCycleRequestBody();
            inValue.Body.ProjectName = ProjectName;
            return ((GlobalReportingSystem.Web.UI.Harvest.ServiceConnectorSoap)(this)).currentCycleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GlobalReportingSystem.Web.UI.Harvest.isProjectExistsResponse GlobalReportingSystem.Web.UI.Harvest.ServiceConnectorSoap.isProjectExists(GlobalReportingSystem.Web.UI.Harvest.isProjectExistsRequest request) {
            return base.Channel.isProjectExists(request);
        }
        
        public bool isProjectExists(string ProjectName) {
            GlobalReportingSystem.Web.UI.Harvest.isProjectExistsRequest inValue = new GlobalReportingSystem.Web.UI.Harvest.isProjectExistsRequest();
            inValue.Body = new GlobalReportingSystem.Web.UI.Harvest.isProjectExistsRequestBody();
            inValue.Body.ProjectName = ProjectName;
            GlobalReportingSystem.Web.UI.Harvest.isProjectExistsResponse retVal = ((GlobalReportingSystem.Web.UI.Harvest.ServiceConnectorSoap)(this)).isProjectExists(inValue);
            return retVal.Body.isProjectExistsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GlobalReportingSystem.Web.UI.Harvest.isProjectExistsResponse> GlobalReportingSystem.Web.UI.Harvest.ServiceConnectorSoap.isProjectExistsAsync(GlobalReportingSystem.Web.UI.Harvest.isProjectExistsRequest request) {
            return base.Channel.isProjectExistsAsync(request);
        }
        
        public System.Threading.Tasks.Task<GlobalReportingSystem.Web.UI.Harvest.isProjectExistsResponse> isProjectExistsAsync(string ProjectName) {
            GlobalReportingSystem.Web.UI.Harvest.isProjectExistsRequest inValue = new GlobalReportingSystem.Web.UI.Harvest.isProjectExistsRequest();
            inValue.Body = new GlobalReportingSystem.Web.UI.Harvest.isProjectExistsRequestBody();
            inValue.Body.ProjectName = ProjectName;
            return ((GlobalReportingSystem.Web.UI.Harvest.ServiceConnectorSoap)(this)).isProjectExistsAsync(inValue);
        }
    }
}
