//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalReportingSystem.Web.UI.ExecutorService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ExecutorService.ExecutorSoap")]
    public interface ExecutorSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RunTests", ReplyAction="*")]
        void RunTests(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RunTests", ReplyAction="*")]
        System.Threading.Tasks.Task RunTestsAsync(int id);
        
        // CODEGEN: Generating message contract since element name ip from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendConsoleCommand", ReplyAction="*")]
        GlobalReportingSystem.Web.UI.ExecutorService.SendConsoleCommandResponse SendConsoleCommand(GlobalReportingSystem.Web.UI.ExecutorService.SendConsoleCommandRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendConsoleCommand", ReplyAction="*")]
        System.Threading.Tasks.Task<GlobalReportingSystem.Web.UI.ExecutorService.SendConsoleCommandResponse> SendConsoleCommandAsync(GlobalReportingSystem.Web.UI.ExecutorService.SendConsoleCommandRequest request);
        
        // CODEGEN: Generating message contract since element name GetAutocompleteResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAutocomplete", ReplyAction="*")]
        GlobalReportingSystem.Web.UI.ExecutorService.GetAutocompleteResponse GetAutocomplete(GlobalReportingSystem.Web.UI.ExecutorService.GetAutocompleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAutocomplete", ReplyAction="*")]
        System.Threading.Tasks.Task<GlobalReportingSystem.Web.UI.ExecutorService.GetAutocompleteResponse> GetAutocompleteAsync(GlobalReportingSystem.Web.UI.ExecutorService.GetAutocompleteRequest request);
        
        // CODEGEN: Generating message contract since element name PingByIDResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PingByID", ReplyAction="*")]
        GlobalReportingSystem.Web.UI.ExecutorService.PingByIDResponse PingByID(GlobalReportingSystem.Web.UI.ExecutorService.PingByIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PingByID", ReplyAction="*")]
        System.Threading.Tasks.Task<GlobalReportingSystem.Web.UI.ExecutorService.PingByIDResponse> PingByIDAsync(GlobalReportingSystem.Web.UI.ExecutorService.PingByIDRequest request);
        
        // CODEGEN: Generating message contract since element name IP from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PingByIP", ReplyAction="*")]
        GlobalReportingSystem.Web.UI.ExecutorService.PingByIPResponse PingByIP(GlobalReportingSystem.Web.UI.ExecutorService.PingByIPRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PingByIP", ReplyAction="*")]
        System.Threading.Tasks.Task<GlobalReportingSystem.Web.UI.ExecutorService.PingByIPResponse> PingByIPAsync(GlobalReportingSystem.Web.UI.ExecutorService.PingByIPRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/syncSchedule", ReplyAction="*")]
        void syncSchedule(int clientID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/syncSchedule", ReplyAction="*")]
        System.Threading.Tasks.Task syncScheduleAsync(int clientID);
        
        // CODEGEN: Generating message contract since element name ip from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendCommandToMachine", ReplyAction="*")]
        GlobalReportingSystem.Web.UI.ExecutorService.SendCommandToMachineResponse SendCommandToMachine(GlobalReportingSystem.Web.UI.ExecutorService.SendCommandToMachineRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendCommandToMachine", ReplyAction="*")]
        System.Threading.Tasks.Task<GlobalReportingSystem.Web.UI.ExecutorService.SendCommandToMachineResponse> SendCommandToMachineAsync(GlobalReportingSystem.Web.UI.ExecutorService.SendCommandToMachineRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendConsoleCommandRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendConsoleCommand", Namespace="http://tempuri.org/", Order=0)]
        public GlobalReportingSystem.Web.UI.ExecutorService.SendConsoleCommandRequestBody Body;
        
        public SendConsoleCommandRequest() {
        }
        
        public SendConsoleCommandRequest(GlobalReportingSystem.Web.UI.ExecutorService.SendConsoleCommandRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendConsoleCommandRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ip;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string command;
        
        public SendConsoleCommandRequestBody() {
        }
        
        public SendConsoleCommandRequestBody(string ip, string command) {
            this.ip = ip;
            this.command = command;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendConsoleCommandResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendConsoleCommandResponse", Namespace="http://tempuri.org/", Order=0)]
        public GlobalReportingSystem.Web.UI.ExecutorService.SendConsoleCommandResponseBody Body;
        
        public SendConsoleCommandResponse() {
        }
        
        public SendConsoleCommandResponse(GlobalReportingSystem.Web.UI.ExecutorService.SendConsoleCommandResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendConsoleCommandResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendConsoleCommandResult;
        
        public SendConsoleCommandResponseBody() {
        }
        
        public SendConsoleCommandResponseBody(string SendConsoleCommandResult) {
            this.SendConsoleCommandResult = SendConsoleCommandResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAutocompleteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAutocomplete", Namespace="http://tempuri.org/", Order=0)]
        public GlobalReportingSystem.Web.UI.ExecutorService.GetAutocompleteRequestBody Body;
        
        public GetAutocompleteRequest() {
        }
        
        public GetAutocompleteRequest(GlobalReportingSystem.Web.UI.ExecutorService.GetAutocompleteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAutocompleteRequestBody {
        
        public GetAutocompleteRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAutocompleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAutocompleteResponse", Namespace="http://tempuri.org/", Order=0)]
        public GlobalReportingSystem.Web.UI.ExecutorService.GetAutocompleteResponseBody Body;
        
        public GetAutocompleteResponse() {
        }
        
        public GetAutocompleteResponse(GlobalReportingSystem.Web.UI.ExecutorService.GetAutocompleteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAutocompleteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public GlobalReportingSystem.Web.UI.ExecutorService.ArrayOfString GetAutocompleteResult;
        
        public GetAutocompleteResponseBody() {
        }
        
        public GetAutocompleteResponseBody(GlobalReportingSystem.Web.UI.ExecutorService.ArrayOfString GetAutocompleteResult) {
            this.GetAutocompleteResult = GetAutocompleteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PingByIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PingByID", Namespace="http://tempuri.org/", Order=0)]
        public GlobalReportingSystem.Web.UI.ExecutorService.PingByIDRequestBody Body;
        
        public PingByIDRequest() {
        }
        
        public PingByIDRequest(GlobalReportingSystem.Web.UI.ExecutorService.PingByIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PingByIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ID;
        
        public PingByIDRequestBody() {
        }
        
        public PingByIDRequestBody(int ID) {
            this.ID = ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PingByIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PingByIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public GlobalReportingSystem.Web.UI.ExecutorService.PingByIDResponseBody Body;
        
        public PingByIDResponse() {
        }
        
        public PingByIDResponse(GlobalReportingSystem.Web.UI.ExecutorService.PingByIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PingByIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PingByIDResult;
        
        public PingByIDResponseBody() {
        }
        
        public PingByIDResponseBody(string PingByIDResult) {
            this.PingByIDResult = PingByIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PingByIPRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PingByIP", Namespace="http://tempuri.org/", Order=0)]
        public GlobalReportingSystem.Web.UI.ExecutorService.PingByIPRequestBody Body;
        
        public PingByIPRequest() {
        }
        
        public PingByIPRequest(GlobalReportingSystem.Web.UI.ExecutorService.PingByIPRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PingByIPRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string IP;
        
        public PingByIPRequestBody() {
        }
        
        public PingByIPRequestBody(string IP) {
            this.IP = IP;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PingByIPResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PingByIPResponse", Namespace="http://tempuri.org/", Order=0)]
        public GlobalReportingSystem.Web.UI.ExecutorService.PingByIPResponseBody Body;
        
        public PingByIPResponse() {
        }
        
        public PingByIPResponse(GlobalReportingSystem.Web.UI.ExecutorService.PingByIPResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PingByIPResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PingByIPResult;
        
        public PingByIPResponseBody() {
        }
        
        public PingByIPResponseBody(string PingByIPResult) {
            this.PingByIPResult = PingByIPResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendCommandToMachineRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendCommandToMachine", Namespace="http://tempuri.org/", Order=0)]
        public GlobalReportingSystem.Web.UI.ExecutorService.SendCommandToMachineRequestBody Body;
        
        public SendCommandToMachineRequest() {
        }
        
        public SendCommandToMachineRequest(GlobalReportingSystem.Web.UI.ExecutorService.SendCommandToMachineRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendCommandToMachineRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ip;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string command;
        
        public SendCommandToMachineRequestBody() {
        }
        
        public SendCommandToMachineRequestBody(string ip, string command) {
            this.ip = ip;
            this.command = command;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendCommandToMachineResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendCommandToMachineResponse", Namespace="http://tempuri.org/", Order=0)]
        public GlobalReportingSystem.Web.UI.ExecutorService.SendCommandToMachineResponseBody Body;
        
        public SendCommandToMachineResponse() {
        }
        
        public SendCommandToMachineResponse(GlobalReportingSystem.Web.UI.ExecutorService.SendCommandToMachineResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SendCommandToMachineResponseBody {
        
        public SendCommandToMachineResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ExecutorSoapChannel : GlobalReportingSystem.Web.UI.ExecutorService.ExecutorSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExecutorSoapClient : System.ServiceModel.ClientBase<GlobalReportingSystem.Web.UI.ExecutorService.ExecutorSoap>, GlobalReportingSystem.Web.UI.ExecutorService.ExecutorSoap {
        
        public ExecutorSoapClient() {
        }
        
        public ExecutorSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExecutorSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExecutorSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExecutorSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void RunTests(int id) {
            base.Channel.RunTests(id);
        }
        
        public System.Threading.Tasks.Task RunTestsAsync(int id) {
            return base.Channel.RunTestsAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GlobalReportingSystem.Web.UI.ExecutorService.SendConsoleCommandResponse GlobalReportingSystem.Web.UI.ExecutorService.ExecutorSoap.SendConsoleCommand(GlobalReportingSystem.Web.UI.ExecutorService.SendConsoleCommandRequest request) {
            return base.Channel.SendConsoleCommand(request);
        }
        
        public string SendConsoleCommand(string ip, string command) {
            GlobalReportingSystem.Web.UI.ExecutorService.SendConsoleCommandRequest inValue = new GlobalReportingSystem.Web.UI.ExecutorService.SendConsoleCommandRequest();
            inValue.Body = new GlobalReportingSystem.Web.UI.ExecutorService.SendConsoleCommandRequestBody();
            inValue.Body.ip = ip;
            inValue.Body.command = command;
            GlobalReportingSystem.Web.UI.ExecutorService.SendConsoleCommandResponse retVal = ((GlobalReportingSystem.Web.UI.ExecutorService.ExecutorSoap)(this)).SendConsoleCommand(inValue);
            return retVal.Body.SendConsoleCommandResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GlobalReportingSystem.Web.UI.ExecutorService.SendConsoleCommandResponse> GlobalReportingSystem.Web.UI.ExecutorService.ExecutorSoap.SendConsoleCommandAsync(GlobalReportingSystem.Web.UI.ExecutorService.SendConsoleCommandRequest request) {
            return base.Channel.SendConsoleCommandAsync(request);
        }
        
        public System.Threading.Tasks.Task<GlobalReportingSystem.Web.UI.ExecutorService.SendConsoleCommandResponse> SendConsoleCommandAsync(string ip, string command) {
            GlobalReportingSystem.Web.UI.ExecutorService.SendConsoleCommandRequest inValue = new GlobalReportingSystem.Web.UI.ExecutorService.SendConsoleCommandRequest();
            inValue.Body = new GlobalReportingSystem.Web.UI.ExecutorService.SendConsoleCommandRequestBody();
            inValue.Body.ip = ip;
            inValue.Body.command = command;
            return ((GlobalReportingSystem.Web.UI.ExecutorService.ExecutorSoap)(this)).SendConsoleCommandAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GlobalReportingSystem.Web.UI.ExecutorService.GetAutocompleteResponse GlobalReportingSystem.Web.UI.ExecutorService.ExecutorSoap.GetAutocomplete(GlobalReportingSystem.Web.UI.ExecutorService.GetAutocompleteRequest request) {
            return base.Channel.GetAutocomplete(request);
        }
        
        public GlobalReportingSystem.Web.UI.ExecutorService.ArrayOfString GetAutocomplete() {
            GlobalReportingSystem.Web.UI.ExecutorService.GetAutocompleteRequest inValue = new GlobalReportingSystem.Web.UI.ExecutorService.GetAutocompleteRequest();
            inValue.Body = new GlobalReportingSystem.Web.UI.ExecutorService.GetAutocompleteRequestBody();
            GlobalReportingSystem.Web.UI.ExecutorService.GetAutocompleteResponse retVal = ((GlobalReportingSystem.Web.UI.ExecutorService.ExecutorSoap)(this)).GetAutocomplete(inValue);
            return retVal.Body.GetAutocompleteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GlobalReportingSystem.Web.UI.ExecutorService.GetAutocompleteResponse> GlobalReportingSystem.Web.UI.ExecutorService.ExecutorSoap.GetAutocompleteAsync(GlobalReportingSystem.Web.UI.ExecutorService.GetAutocompleteRequest request) {
            return base.Channel.GetAutocompleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<GlobalReportingSystem.Web.UI.ExecutorService.GetAutocompleteResponse> GetAutocompleteAsync() {
            GlobalReportingSystem.Web.UI.ExecutorService.GetAutocompleteRequest inValue = new GlobalReportingSystem.Web.UI.ExecutorService.GetAutocompleteRequest();
            inValue.Body = new GlobalReportingSystem.Web.UI.ExecutorService.GetAutocompleteRequestBody();
            return ((GlobalReportingSystem.Web.UI.ExecutorService.ExecutorSoap)(this)).GetAutocompleteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GlobalReportingSystem.Web.UI.ExecutorService.PingByIDResponse GlobalReportingSystem.Web.UI.ExecutorService.ExecutorSoap.PingByID(GlobalReportingSystem.Web.UI.ExecutorService.PingByIDRequest request) {
            return base.Channel.PingByID(request);
        }
        
        public string PingByID(int ID) {
            GlobalReportingSystem.Web.UI.ExecutorService.PingByIDRequest inValue = new GlobalReportingSystem.Web.UI.ExecutorService.PingByIDRequest();
            inValue.Body = new GlobalReportingSystem.Web.UI.ExecutorService.PingByIDRequestBody();
            inValue.Body.ID = ID;
            GlobalReportingSystem.Web.UI.ExecutorService.PingByIDResponse retVal = ((GlobalReportingSystem.Web.UI.ExecutorService.ExecutorSoap)(this)).PingByID(inValue);
            return retVal.Body.PingByIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GlobalReportingSystem.Web.UI.ExecutorService.PingByIDResponse> GlobalReportingSystem.Web.UI.ExecutorService.ExecutorSoap.PingByIDAsync(GlobalReportingSystem.Web.UI.ExecutorService.PingByIDRequest request) {
            return base.Channel.PingByIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<GlobalReportingSystem.Web.UI.ExecutorService.PingByIDResponse> PingByIDAsync(int ID) {
            GlobalReportingSystem.Web.UI.ExecutorService.PingByIDRequest inValue = new GlobalReportingSystem.Web.UI.ExecutorService.PingByIDRequest();
            inValue.Body = new GlobalReportingSystem.Web.UI.ExecutorService.PingByIDRequestBody();
            inValue.Body.ID = ID;
            return ((GlobalReportingSystem.Web.UI.ExecutorService.ExecutorSoap)(this)).PingByIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GlobalReportingSystem.Web.UI.ExecutorService.PingByIPResponse GlobalReportingSystem.Web.UI.ExecutorService.ExecutorSoap.PingByIP(GlobalReportingSystem.Web.UI.ExecutorService.PingByIPRequest request) {
            return base.Channel.PingByIP(request);
        }
        
        public string PingByIP(string IP) {
            GlobalReportingSystem.Web.UI.ExecutorService.PingByIPRequest inValue = new GlobalReportingSystem.Web.UI.ExecutorService.PingByIPRequest();
            inValue.Body = new GlobalReportingSystem.Web.UI.ExecutorService.PingByIPRequestBody();
            inValue.Body.IP = IP;
            GlobalReportingSystem.Web.UI.ExecutorService.PingByIPResponse retVal = ((GlobalReportingSystem.Web.UI.ExecutorService.ExecutorSoap)(this)).PingByIP(inValue);
            return retVal.Body.PingByIPResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GlobalReportingSystem.Web.UI.ExecutorService.PingByIPResponse> GlobalReportingSystem.Web.UI.ExecutorService.ExecutorSoap.PingByIPAsync(GlobalReportingSystem.Web.UI.ExecutorService.PingByIPRequest request) {
            return base.Channel.PingByIPAsync(request);
        }
        
        public System.Threading.Tasks.Task<GlobalReportingSystem.Web.UI.ExecutorService.PingByIPResponse> PingByIPAsync(string IP) {
            GlobalReportingSystem.Web.UI.ExecutorService.PingByIPRequest inValue = new GlobalReportingSystem.Web.UI.ExecutorService.PingByIPRequest();
            inValue.Body = new GlobalReportingSystem.Web.UI.ExecutorService.PingByIPRequestBody();
            inValue.Body.IP = IP;
            return ((GlobalReportingSystem.Web.UI.ExecutorService.ExecutorSoap)(this)).PingByIPAsync(inValue);
        }
        
        public void syncSchedule(int clientID) {
            base.Channel.syncSchedule(clientID);
        }
        
        public System.Threading.Tasks.Task syncScheduleAsync(int clientID) {
            return base.Channel.syncScheduleAsync(clientID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GlobalReportingSystem.Web.UI.ExecutorService.SendCommandToMachineResponse GlobalReportingSystem.Web.UI.ExecutorService.ExecutorSoap.SendCommandToMachine(GlobalReportingSystem.Web.UI.ExecutorService.SendCommandToMachineRequest request) {
            return base.Channel.SendCommandToMachine(request);
        }
        
        public void SendCommandToMachine(string ip, string command) {
            GlobalReportingSystem.Web.UI.ExecutorService.SendCommandToMachineRequest inValue = new GlobalReportingSystem.Web.UI.ExecutorService.SendCommandToMachineRequest();
            inValue.Body = new GlobalReportingSystem.Web.UI.ExecutorService.SendCommandToMachineRequestBody();
            inValue.Body.ip = ip;
            inValue.Body.command = command;
            GlobalReportingSystem.Web.UI.ExecutorService.SendCommandToMachineResponse retVal = ((GlobalReportingSystem.Web.UI.ExecutorService.ExecutorSoap)(this)).SendCommandToMachine(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GlobalReportingSystem.Web.UI.ExecutorService.SendCommandToMachineResponse> GlobalReportingSystem.Web.UI.ExecutorService.ExecutorSoap.SendCommandToMachineAsync(GlobalReportingSystem.Web.UI.ExecutorService.SendCommandToMachineRequest request) {
            return base.Channel.SendCommandToMachineAsync(request);
        }
        
        public System.Threading.Tasks.Task<GlobalReportingSystem.Web.UI.ExecutorService.SendCommandToMachineResponse> SendCommandToMachineAsync(string ip, string command) {
            GlobalReportingSystem.Web.UI.ExecutorService.SendCommandToMachineRequest inValue = new GlobalReportingSystem.Web.UI.ExecutorService.SendCommandToMachineRequest();
            inValue.Body = new GlobalReportingSystem.Web.UI.ExecutorService.SendCommandToMachineRequestBody();
            inValue.Body.ip = ip;
            inValue.Body.command = command;
            return ((GlobalReportingSystem.Web.UI.ExecutorService.ExecutorSoap)(this)).SendCommandToMachineAsync(inValue);
        }
    }
}
