//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GRSExecutor.GrsAgent {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webserver.agent.grs.thomsonreuters.com/")]
    public partial class Exception : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webserver.agent.grs.thomsonreuters.com/", ConfigurationName="GrsAgent.AgentWebMethods")]
    public interface AgentWebMethods {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webserver.agent.grs.thomsonreuters.com/AgentWebMethods/stopRequest", ReplyAction="http://webserver.agent.grs.thomsonreuters.com/AgentWebMethods/stopResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void stop();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webserver.agent.grs.thomsonreuters.com/AgentWebMethods/stopRequest", ReplyAction="http://webserver.agent.grs.thomsonreuters.com/AgentWebMethods/stopResponse")]
        System.Threading.Tasks.Task stopAsync();
        
        // CODEGEN: Parameter 'id' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webserver.agent.grs.thomsonreuters.com/AgentWebMethods/startLoadbalancedRe" +
            "quest", ReplyAction="http://webserver.agent.grs.thomsonreuters.com/AgentWebMethods/startLoadbalancedRe" +
            "sponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GRSExecutor.GrsAgent.startLoadbalancedResponse startLoadbalanced(GRSExecutor.GrsAgent.startLoadbalancedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webserver.agent.grs.thomsonreuters.com/AgentWebMethods/startLoadbalancedRe" +
            "quest", ReplyAction="http://webserver.agent.grs.thomsonreuters.com/AgentWebMethods/startLoadbalancedRe" +
            "sponse")]
        System.Threading.Tasks.Task<GRSExecutor.GrsAgent.startLoadbalancedResponse> startLoadbalancedAsync(GRSExecutor.GrsAgent.startLoadbalancedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webserver.agent.grs.thomsonreuters.com/AgentWebMethods/removeLastReportsRe" +
            "quest", ReplyAction="http://webserver.agent.grs.thomsonreuters.com/AgentWebMethods/removeLastReportsRe" +
            "sponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void removeLastReports();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webserver.agent.grs.thomsonreuters.com/AgentWebMethods/removeLastReportsRe" +
            "quest", ReplyAction="http://webserver.agent.grs.thomsonreuters.com/AgentWebMethods/removeLastReportsRe" +
            "sponse")]
        System.Threading.Tasks.Task removeLastReportsAsync();
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webserver.agent.grs.thomsonreuters.com/AgentWebMethods/getLastReportIdsLbR" +
            "equest", ReplyAction="http://webserver.agent.grs.thomsonreuters.com/AgentWebMethods/getLastReportIdsLbR" +
            "esponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GRSExecutor.GrsAgent.getLastReportIdsLbResponse getLastReportIdsLb(GRSExecutor.GrsAgent.getLastReportIdsLbRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webserver.agent.grs.thomsonreuters.com/AgentWebMethods/getLastReportIdsLbR" +
            "equest", ReplyAction="http://webserver.agent.grs.thomsonreuters.com/AgentWebMethods/getLastReportIdsLbR" +
            "esponse")]
        System.Threading.Tasks.Task<GRSExecutor.GrsAgent.getLastReportIdsLbResponse> getLastReportIdsLbAsync(GRSExecutor.GrsAgent.getLastReportIdsLbRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webserver.agent.grs.thomsonreuters.com/AgentWebMethods/executeCustomComman" +
            "dRequest", ReplyAction="http://webserver.agent.grs.thomsonreuters.com/AgentWebMethods/executeCustomComman" +
            "dResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GRSExecutor.GrsAgent.Exception), Action="http://webserver.agent.grs.thomsonreuters.com/AgentWebMethods/executeCustomComman" +
            "d/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GRSExecutor.GrsAgent.executeCustomCommandResponse executeCustomCommand(GRSExecutor.GrsAgent.executeCustomCommandRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webserver.agent.grs.thomsonreuters.com/AgentWebMethods/executeCustomComman" +
            "dRequest", ReplyAction="http://webserver.agent.grs.thomsonreuters.com/AgentWebMethods/executeCustomComman" +
            "dResponse")]
        System.Threading.Tasks.Task<GRSExecutor.GrsAgent.executeCustomCommandResponse> executeCustomCommandAsync(GRSExecutor.GrsAgent.executeCustomCommandRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webserver.agent.grs.thomsonreuters.com/AgentWebMethods/getVersionRequest", ReplyAction="http://webserver.agent.grs.thomsonreuters.com/AgentWebMethods/getVersionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GRSExecutor.GrsAgent.getVersionResponse getVersion(GRSExecutor.GrsAgent.getVersionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webserver.agent.grs.thomsonreuters.com/AgentWebMethods/getVersionRequest", ReplyAction="http://webserver.agent.grs.thomsonreuters.com/AgentWebMethods/getVersionResponse")]
        System.Threading.Tasks.Task<GRSExecutor.GrsAgent.getVersionResponse> getVersionAsync(GRSExecutor.GrsAgent.getVersionRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webserver.agent.grs.thomsonreuters.com/AgentWebMethods/pingRequest", ReplyAction="http://webserver.agent.grs.thomsonreuters.com/AgentWebMethods/pingResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GRSExecutor.GrsAgent.pingResponse ping(GRSExecutor.GrsAgent.pingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webserver.agent.grs.thomsonreuters.com/AgentWebMethods/pingRequest", ReplyAction="http://webserver.agent.grs.thomsonreuters.com/AgentWebMethods/pingResponse")]
        System.Threading.Tasks.Task<GRSExecutor.GrsAgent.pingResponse> pingAsync(GRSExecutor.GrsAgent.pingRequest request);
        
        // CODEGEN: Parameter 'id' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webserver.agent.grs.thomsonreuters.com/AgentWebMethods/startLinearRequest", ReplyAction="http://webserver.agent.grs.thomsonreuters.com/AgentWebMethods/startLinearResponse" +
            "")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GRSExecutor.GrsAgent.startLinearResponse startLinear(GRSExecutor.GrsAgent.startLinearRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webserver.agent.grs.thomsonreuters.com/AgentWebMethods/startLinearRequest", ReplyAction="http://webserver.agent.grs.thomsonreuters.com/AgentWebMethods/startLinearResponse" +
            "")]
        System.Threading.Tasks.Task<GRSExecutor.GrsAgent.startLinearResponse> startLinearAsync(GRSExecutor.GrsAgent.startLinearRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="startLoadbalanced", WrapperNamespace="http://webserver.agent.grs.thomsonreuters.com/", IsWrapped=true)]
    public partial class startLoadbalancedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webserver.agent.grs.thomsonreuters.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public startLoadbalancedRequest() {
        }
        
        public startLoadbalancedRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="startLoadbalancedResponse", WrapperNamespace="http://webserver.agent.grs.thomsonreuters.com/", IsWrapped=true)]
    public partial class startLoadbalancedResponse {
        
        public startLoadbalancedResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getLastReportIdsLb", WrapperNamespace="http://webserver.agent.grs.thomsonreuters.com/", IsWrapped=true)]
    public partial class getLastReportIdsLbRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webserver.agent.grs.thomsonreuters.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webserver.agent.grs.thomsonreuters.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool arg1;
        
        public getLastReportIdsLbRequest() {
        }
        
        public getLastReportIdsLbRequest(int arg0, bool arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getLastReportIdsLbResponse", WrapperNamespace="http://webserver.agent.grs.thomsonreuters.com/", IsWrapped=true)]
    public partial class getLastReportIdsLbResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webserver.agent.grs.thomsonreuters.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public getLastReportIdsLbResponse() {
        }
        
        public getLastReportIdsLbResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="executeCustomCommand", WrapperNamespace="http://webserver.agent.grs.thomsonreuters.com/", IsWrapped=true)]
    public partial class executeCustomCommandRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webserver.agent.grs.thomsonreuters.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string command;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webserver.agent.grs.thomsonreuters.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @params;
        
        public executeCustomCommandRequest() {
        }
        
        public executeCustomCommandRequest(string command, string @params) {
            this.command = command;
            this.@params = @params;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="executeCustomCommandResponse", WrapperNamespace="http://webserver.agent.grs.thomsonreuters.com/", IsWrapped=true)]
    public partial class executeCustomCommandResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webserver.agent.grs.thomsonreuters.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public executeCustomCommandResponse() {
        }
        
        public executeCustomCommandResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getVersion", WrapperNamespace="http://webserver.agent.grs.thomsonreuters.com/", IsWrapped=true)]
    public partial class getVersionRequest {
        
        public getVersionRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getVersionResponse", WrapperNamespace="http://webserver.agent.grs.thomsonreuters.com/", IsWrapped=true)]
    public partial class getVersionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webserver.agent.grs.thomsonreuters.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getVersionResponse() {
        }
        
        public getVersionResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ping", WrapperNamespace="http://webserver.agent.grs.thomsonreuters.com/", IsWrapped=true)]
    public partial class pingRequest {
        
        public pingRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pingResponse", WrapperNamespace="http://webserver.agent.grs.thomsonreuters.com/", IsWrapped=true)]
    public partial class pingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webserver.agent.grs.thomsonreuters.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public pingResponse() {
        }
        
        public pingResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="startLinear", WrapperNamespace="http://webserver.agent.grs.thomsonreuters.com/", IsWrapped=true)]
    public partial class startLinearRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webserver.agent.grs.thomsonreuters.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public startLinearRequest() {
        }
        
        public startLinearRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="startLinearResponse", WrapperNamespace="http://webserver.agent.grs.thomsonreuters.com/", IsWrapped=true)]
    public partial class startLinearResponse {
        
        public startLinearResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AgentWebMethodsChannel : GRSExecutor.GrsAgent.AgentWebMethods, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AgentWebMethodsClient : System.ServiceModel.ClientBase<GRSExecutor.GrsAgent.AgentWebMethods>, GRSExecutor.GrsAgent.AgentWebMethods {
        
        public AgentWebMethodsClient() {
        }
        
        public AgentWebMethodsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AgentWebMethodsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AgentWebMethodsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AgentWebMethodsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void stop() {
            base.Channel.stop();
        }
        
        public System.Threading.Tasks.Task stopAsync() {
            return base.Channel.stopAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GRSExecutor.GrsAgent.startLoadbalancedResponse GRSExecutor.GrsAgent.AgentWebMethods.startLoadbalanced(GRSExecutor.GrsAgent.startLoadbalancedRequest request) {
            return base.Channel.startLoadbalanced(request);
        }
        
        public void startLoadbalanced(int id) {
            GRSExecutor.GrsAgent.startLoadbalancedRequest inValue = new GRSExecutor.GrsAgent.startLoadbalancedRequest();
            inValue.id = id;
            GRSExecutor.GrsAgent.startLoadbalancedResponse retVal = ((GRSExecutor.GrsAgent.AgentWebMethods)(this)).startLoadbalanced(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GRSExecutor.GrsAgent.startLoadbalancedResponse> GRSExecutor.GrsAgent.AgentWebMethods.startLoadbalancedAsync(GRSExecutor.GrsAgent.startLoadbalancedRequest request) {
            return base.Channel.startLoadbalancedAsync(request);
        }
        
        public System.Threading.Tasks.Task<GRSExecutor.GrsAgent.startLoadbalancedResponse> startLoadbalancedAsync(int id) {
            GRSExecutor.GrsAgent.startLoadbalancedRequest inValue = new GRSExecutor.GrsAgent.startLoadbalancedRequest();
            inValue.id = id;
            return ((GRSExecutor.GrsAgent.AgentWebMethods)(this)).startLoadbalancedAsync(inValue);
        }
        
        public void removeLastReports() {
            base.Channel.removeLastReports();
        }
        
        public System.Threading.Tasks.Task removeLastReportsAsync() {
            return base.Channel.removeLastReportsAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GRSExecutor.GrsAgent.getLastReportIdsLbResponse GRSExecutor.GrsAgent.AgentWebMethods.getLastReportIdsLb(GRSExecutor.GrsAgent.getLastReportIdsLbRequest request) {
            return base.Channel.getLastReportIdsLb(request);
        }
        
        public bool getLastReportIdsLb(int arg0, bool arg1) {
            GRSExecutor.GrsAgent.getLastReportIdsLbRequest inValue = new GRSExecutor.GrsAgent.getLastReportIdsLbRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            GRSExecutor.GrsAgent.getLastReportIdsLbResponse retVal = ((GRSExecutor.GrsAgent.AgentWebMethods)(this)).getLastReportIdsLb(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GRSExecutor.GrsAgent.getLastReportIdsLbResponse> GRSExecutor.GrsAgent.AgentWebMethods.getLastReportIdsLbAsync(GRSExecutor.GrsAgent.getLastReportIdsLbRequest request) {
            return base.Channel.getLastReportIdsLbAsync(request);
        }
        
        public System.Threading.Tasks.Task<GRSExecutor.GrsAgent.getLastReportIdsLbResponse> getLastReportIdsLbAsync(int arg0, bool arg1) {
            GRSExecutor.GrsAgent.getLastReportIdsLbRequest inValue = new GRSExecutor.GrsAgent.getLastReportIdsLbRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((GRSExecutor.GrsAgent.AgentWebMethods)(this)).getLastReportIdsLbAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GRSExecutor.GrsAgent.executeCustomCommandResponse GRSExecutor.GrsAgent.AgentWebMethods.executeCustomCommand(GRSExecutor.GrsAgent.executeCustomCommandRequest request) {
            return base.Channel.executeCustomCommand(request);
        }
        
        public string executeCustomCommand(string command, string @params) {
            GRSExecutor.GrsAgent.executeCustomCommandRequest inValue = new GRSExecutor.GrsAgent.executeCustomCommandRequest();
            inValue.command = command;
            inValue.@params = @params;
            GRSExecutor.GrsAgent.executeCustomCommandResponse retVal = ((GRSExecutor.GrsAgent.AgentWebMethods)(this)).executeCustomCommand(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GRSExecutor.GrsAgent.executeCustomCommandResponse> GRSExecutor.GrsAgent.AgentWebMethods.executeCustomCommandAsync(GRSExecutor.GrsAgent.executeCustomCommandRequest request) {
            return base.Channel.executeCustomCommandAsync(request);
        }
        
        public System.Threading.Tasks.Task<GRSExecutor.GrsAgent.executeCustomCommandResponse> executeCustomCommandAsync(string command, string @params) {
            GRSExecutor.GrsAgent.executeCustomCommandRequest inValue = new GRSExecutor.GrsAgent.executeCustomCommandRequest();
            inValue.command = command;
            inValue.@params = @params;
            return ((GRSExecutor.GrsAgent.AgentWebMethods)(this)).executeCustomCommandAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GRSExecutor.GrsAgent.getVersionResponse GRSExecutor.GrsAgent.AgentWebMethods.getVersion(GRSExecutor.GrsAgent.getVersionRequest request) {
            return base.Channel.getVersion(request);
        }
        
        public string getVersion() {
            GRSExecutor.GrsAgent.getVersionRequest inValue = new GRSExecutor.GrsAgent.getVersionRequest();
            GRSExecutor.GrsAgent.getVersionResponse retVal = ((GRSExecutor.GrsAgent.AgentWebMethods)(this)).getVersion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GRSExecutor.GrsAgent.getVersionResponse> GRSExecutor.GrsAgent.AgentWebMethods.getVersionAsync(GRSExecutor.GrsAgent.getVersionRequest request) {
            return base.Channel.getVersionAsync(request);
        }
        
        public System.Threading.Tasks.Task<GRSExecutor.GrsAgent.getVersionResponse> getVersionAsync() {
            GRSExecutor.GrsAgent.getVersionRequest inValue = new GRSExecutor.GrsAgent.getVersionRequest();
            return ((GRSExecutor.GrsAgent.AgentWebMethods)(this)).getVersionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GRSExecutor.GrsAgent.pingResponse GRSExecutor.GrsAgent.AgentWebMethods.ping(GRSExecutor.GrsAgent.pingRequest request) {
            return base.Channel.ping(request);
        }
        
        public bool ping() {
            GRSExecutor.GrsAgent.pingRequest inValue = new GRSExecutor.GrsAgent.pingRequest();
            GRSExecutor.GrsAgent.pingResponse retVal = ((GRSExecutor.GrsAgent.AgentWebMethods)(this)).ping(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GRSExecutor.GrsAgent.pingResponse> GRSExecutor.GrsAgent.AgentWebMethods.pingAsync(GRSExecutor.GrsAgent.pingRequest request) {
            return base.Channel.pingAsync(request);
        }
        
        public System.Threading.Tasks.Task<GRSExecutor.GrsAgent.pingResponse> pingAsync() {
            GRSExecutor.GrsAgent.pingRequest inValue = new GRSExecutor.GrsAgent.pingRequest();
            return ((GRSExecutor.GrsAgent.AgentWebMethods)(this)).pingAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GRSExecutor.GrsAgent.startLinearResponse GRSExecutor.GrsAgent.AgentWebMethods.startLinear(GRSExecutor.GrsAgent.startLinearRequest request) {
            return base.Channel.startLinear(request);
        }
        
        public void startLinear(int id) {
            GRSExecutor.GrsAgent.startLinearRequest inValue = new GRSExecutor.GrsAgent.startLinearRequest();
            inValue.id = id;
            GRSExecutor.GrsAgent.startLinearResponse retVal = ((GRSExecutor.GrsAgent.AgentWebMethods)(this)).startLinear(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GRSExecutor.GrsAgent.startLinearResponse> GRSExecutor.GrsAgent.AgentWebMethods.startLinearAsync(GRSExecutor.GrsAgent.startLinearRequest request) {
            return base.Channel.startLinearAsync(request);
        }
        
        public System.Threading.Tasks.Task<GRSExecutor.GrsAgent.startLinearResponse> startLinearAsync(int id) {
            GRSExecutor.GrsAgent.startLinearRequest inValue = new GRSExecutor.GrsAgent.startLinearRequest();
            inValue.id = id;
            return ((GRSExecutor.GrsAgent.AgentWebMethods)(this)).startLinearAsync(inValue);
        }
    }
}
