//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalReportingSystem.Web.UI.ExecutorNg {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ng.executor.webclient.agent.grs.thomsonreuters.com/", ConfigurationName="ExecutorNg.ExecutorNgSoap")]
    public interface ExecutorNgSoap {
        
        // CODEGEN: Generating message contract since element name PingByIdResult from namespace http://ng.executor.webclient.agent.grs.thomsonreuters.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ng.executor.webclient.agent.grs.thomsonreuters.com/PingById", ReplyAction="*")]
        GlobalReportingSystem.Web.UI.ExecutorNg.PingByIdResponse PingById(GlobalReportingSystem.Web.UI.ExecutorNg.PingByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ng.executor.webclient.agent.grs.thomsonreuters.com/PingById", ReplyAction="*")]
        System.Threading.Tasks.Task<GlobalReportingSystem.Web.UI.ExecutorNg.PingByIdResponse> PingByIdAsync(GlobalReportingSystem.Web.UI.ExecutorNg.PingByIdRequest request);
        
        // CODEGEN: Generating message contract since element name ip from namespace http://ng.executor.webclient.agent.grs.thomsonreuters.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ng.executor.webclient.agent.grs.thomsonreuters.com/PingByIp", ReplyAction="*")]
        GlobalReportingSystem.Web.UI.ExecutorNg.PingByIpResponse PingByIp(GlobalReportingSystem.Web.UI.ExecutorNg.PingByIpRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ng.executor.webclient.agent.grs.thomsonreuters.com/PingByIp", ReplyAction="*")]
        System.Threading.Tasks.Task<GlobalReportingSystem.Web.UI.ExecutorNg.PingByIpResponse> PingByIpAsync(GlobalReportingSystem.Web.UI.ExecutorNg.PingByIpRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ng.executor.webclient.agent.grs.thomsonreuters.com/StartLinear", ReplyAction="*")]
        void StartLinear(int executionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ng.executor.webclient.agent.grs.thomsonreuters.com/StartLinear", ReplyAction="*")]
        System.Threading.Tasks.Task StartLinearAsync(int executionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ng.executor.webclient.agent.grs.thomsonreuters.com/StartLoadBalanced", ReplyAction="*")]
        void StartLoadBalanced(int executionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ng.executor.webclient.agent.grs.thomsonreuters.com/StartLoadBalanced", ReplyAction="*")]
        System.Threading.Tasks.Task StartLoadBalancedAsync(int executionId);
        
        // CODEGEN: Generating message contract since element name ip from namespace http://ng.executor.webclient.agent.grs.thomsonreuters.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ng.executor.webclient.agent.grs.thomsonreuters.com/Stop", ReplyAction="*")]
        GlobalReportingSystem.Web.UI.ExecutorNg.StopResponse Stop(GlobalReportingSystem.Web.UI.ExecutorNg.StopRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ng.executor.webclient.agent.grs.thomsonreuters.com/Stop", ReplyAction="*")]
        System.Threading.Tasks.Task<GlobalReportingSystem.Web.UI.ExecutorNg.StopResponse> StopAsync(GlobalReportingSystem.Web.UI.ExecutorNg.StopRequest request);
        
        // CODEGEN: Generating message contract since element name WaitForLinearRelResultsResult from namespace http://ng.executor.webclient.agent.grs.thomsonreuters.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ng.executor.webclient.agent.grs.thomsonreuters.com/WaitForLinearRelResults" +
            "", ReplyAction="*")]
        GlobalReportingSystem.Web.UI.ExecutorNg.WaitForLinearRelResultsResponse WaitForLinearRelResults(GlobalReportingSystem.Web.UI.ExecutorNg.WaitForLinearRelResultsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ng.executor.webclient.agent.grs.thomsonreuters.com/WaitForLinearRelResults" +
            "", ReplyAction="*")]
        System.Threading.Tasks.Task<GlobalReportingSystem.Web.UI.ExecutorNg.WaitForLinearRelResultsResponse> WaitForLinearRelResultsAsync(GlobalReportingSystem.Web.UI.ExecutorNg.WaitForLinearRelResultsRequest request);
        
        // CODEGEN: Generating message contract since element name WaitForLbRelResultsResult from namespace http://ng.executor.webclient.agent.grs.thomsonreuters.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ng.executor.webclient.agent.grs.thomsonreuters.com/WaitForLbRelResults", ReplyAction="*")]
        GlobalReportingSystem.Web.UI.ExecutorNg.WaitForLbRelResultsResponse WaitForLbRelResults(GlobalReportingSystem.Web.UI.ExecutorNg.WaitForLbRelResultsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ng.executor.webclient.agent.grs.thomsonreuters.com/WaitForLbRelResults", ReplyAction="*")]
        System.Threading.Tasks.Task<GlobalReportingSystem.Web.UI.ExecutorNg.WaitForLbRelResultsResponse> WaitForLbRelResultsAsync(GlobalReportingSystem.Web.UI.ExecutorNg.WaitForLbRelResultsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PingByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PingById", Namespace="http://ng.executor.webclient.agent.grs.thomsonreuters.com/", Order=0)]
        public GlobalReportingSystem.Web.UI.ExecutorNg.PingByIdRequestBody Body;
        
        public PingByIdRequest() {
        }
        
        public PingByIdRequest(GlobalReportingSystem.Web.UI.ExecutorNg.PingByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ng.executor.webclient.agent.grs.thomsonreuters.com/")]
    public partial class PingByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public PingByIdRequestBody() {
        }
        
        public PingByIdRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PingByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PingByIdResponse", Namespace="http://ng.executor.webclient.agent.grs.thomsonreuters.com/", Order=0)]
        public GlobalReportingSystem.Web.UI.ExecutorNg.PingByIdResponseBody Body;
        
        public PingByIdResponse() {
        }
        
        public PingByIdResponse(GlobalReportingSystem.Web.UI.ExecutorNg.PingByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ng.executor.webclient.agent.grs.thomsonreuters.com/")]
    public partial class PingByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PingByIdResult;
        
        public PingByIdResponseBody() {
        }
        
        public PingByIdResponseBody(string PingByIdResult) {
            this.PingByIdResult = PingByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PingByIpRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PingByIp", Namespace="http://ng.executor.webclient.agent.grs.thomsonreuters.com/", Order=0)]
        public GlobalReportingSystem.Web.UI.ExecutorNg.PingByIpRequestBody Body;
        
        public PingByIpRequest() {
        }
        
        public PingByIpRequest(GlobalReportingSystem.Web.UI.ExecutorNg.PingByIpRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ng.executor.webclient.agent.grs.thomsonreuters.com/")]
    public partial class PingByIpRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ip;
        
        public PingByIpRequestBody() {
        }
        
        public PingByIpRequestBody(string ip) {
            this.ip = ip;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PingByIpResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PingByIpResponse", Namespace="http://ng.executor.webclient.agent.grs.thomsonreuters.com/", Order=0)]
        public GlobalReportingSystem.Web.UI.ExecutorNg.PingByIpResponseBody Body;
        
        public PingByIpResponse() {
        }
        
        public PingByIpResponse(GlobalReportingSystem.Web.UI.ExecutorNg.PingByIpResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ng.executor.webclient.agent.grs.thomsonreuters.com/")]
    public partial class PingByIpResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PingByIpResult;
        
        public PingByIpResponseBody() {
        }
        
        public PingByIpResponseBody(string PingByIpResult) {
            this.PingByIpResult = PingByIpResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StopRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Stop", Namespace="http://ng.executor.webclient.agent.grs.thomsonreuters.com/", Order=0)]
        public GlobalReportingSystem.Web.UI.ExecutorNg.StopRequestBody Body;
        
        public StopRequest() {
        }
        
        public StopRequest(GlobalReportingSystem.Web.UI.ExecutorNg.StopRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ng.executor.webclient.agent.grs.thomsonreuters.com/")]
    public partial class StopRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ip;
        
        public StopRequestBody() {
        }
        
        public StopRequestBody(string ip) {
            this.ip = ip;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StopResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StopResponse", Namespace="http://ng.executor.webclient.agent.grs.thomsonreuters.com/", Order=0)]
        public GlobalReportingSystem.Web.UI.ExecutorNg.StopResponseBody Body;
        
        public StopResponse() {
        }
        
        public StopResponse(GlobalReportingSystem.Web.UI.ExecutorNg.StopResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class StopResponseBody {
        
        public StopResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WaitForLinearRelResultsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WaitForLinearRelResults", Namespace="http://ng.executor.webclient.agent.grs.thomsonreuters.com/", Order=0)]
        public GlobalReportingSystem.Web.UI.ExecutorNg.WaitForLinearRelResultsRequestBody Body;
        
        public WaitForLinearRelResultsRequest() {
        }
        
        public WaitForLinearRelResultsRequest(GlobalReportingSystem.Web.UI.ExecutorNg.WaitForLinearRelResultsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ng.executor.webclient.agent.grs.thomsonreuters.com/")]
    public partial class WaitForLinearRelResultsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int executionId;
        
        public WaitForLinearRelResultsRequestBody() {
        }
        
        public WaitForLinearRelResultsRequestBody(int executionId) {
            this.executionId = executionId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WaitForLinearRelResultsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WaitForLinearRelResultsResponse", Namespace="http://ng.executor.webclient.agent.grs.thomsonreuters.com/", Order=0)]
        public GlobalReportingSystem.Web.UI.ExecutorNg.WaitForLinearRelResultsResponseBody Body;
        
        public WaitForLinearRelResultsResponse() {
        }
        
        public WaitForLinearRelResultsResponse(GlobalReportingSystem.Web.UI.ExecutorNg.WaitForLinearRelResultsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ng.executor.webclient.agent.grs.thomsonreuters.com/")]
    public partial class WaitForLinearRelResultsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string WaitForLinearRelResultsResult;
        
        public WaitForLinearRelResultsResponseBody() {
        }
        
        public WaitForLinearRelResultsResponseBody(string WaitForLinearRelResultsResult) {
            this.WaitForLinearRelResultsResult = WaitForLinearRelResultsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WaitForLbRelResultsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WaitForLbRelResults", Namespace="http://ng.executor.webclient.agent.grs.thomsonreuters.com/", Order=0)]
        public GlobalReportingSystem.Web.UI.ExecutorNg.WaitForLbRelResultsRequestBody Body;
        
        public WaitForLbRelResultsRequest() {
        }
        
        public WaitForLbRelResultsRequest(GlobalReportingSystem.Web.UI.ExecutorNg.WaitForLbRelResultsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ng.executor.webclient.agent.grs.thomsonreuters.com/")]
    public partial class WaitForLbRelResultsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int executionId;
        
        public WaitForLbRelResultsRequestBody() {
        }
        
        public WaitForLbRelResultsRequestBody(int executionId) {
            this.executionId = executionId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WaitForLbRelResultsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WaitForLbRelResultsResponse", Namespace="http://ng.executor.webclient.agent.grs.thomsonreuters.com/", Order=0)]
        public GlobalReportingSystem.Web.UI.ExecutorNg.WaitForLbRelResultsResponseBody Body;
        
        public WaitForLbRelResultsResponse() {
        }
        
        public WaitForLbRelResultsResponse(GlobalReportingSystem.Web.UI.ExecutorNg.WaitForLbRelResultsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ng.executor.webclient.agent.grs.thomsonreuters.com/")]
    public partial class WaitForLbRelResultsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string WaitForLbRelResultsResult;
        
        public WaitForLbRelResultsResponseBody() {
        }
        
        public WaitForLbRelResultsResponseBody(string WaitForLbRelResultsResult) {
            this.WaitForLbRelResultsResult = WaitForLbRelResultsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ExecutorNgSoapChannel : GlobalReportingSystem.Web.UI.ExecutorNg.ExecutorNgSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExecutorNgSoapClient : System.ServiceModel.ClientBase<GlobalReportingSystem.Web.UI.ExecutorNg.ExecutorNgSoap>, GlobalReportingSystem.Web.UI.ExecutorNg.ExecutorNgSoap {
        
        public ExecutorNgSoapClient() {
        }
        
        public ExecutorNgSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExecutorNgSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExecutorNgSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExecutorNgSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GlobalReportingSystem.Web.UI.ExecutorNg.PingByIdResponse GlobalReportingSystem.Web.UI.ExecutorNg.ExecutorNgSoap.PingById(GlobalReportingSystem.Web.UI.ExecutorNg.PingByIdRequest request) {
            return base.Channel.PingById(request);
        }
        
        public string PingById(int id) {
            GlobalReportingSystem.Web.UI.ExecutorNg.PingByIdRequest inValue = new GlobalReportingSystem.Web.UI.ExecutorNg.PingByIdRequest();
            inValue.Body = new GlobalReportingSystem.Web.UI.ExecutorNg.PingByIdRequestBody();
            inValue.Body.id = id;
            GlobalReportingSystem.Web.UI.ExecutorNg.PingByIdResponse retVal = ((GlobalReportingSystem.Web.UI.ExecutorNg.ExecutorNgSoap)(this)).PingById(inValue);
            return retVal.Body.PingByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GlobalReportingSystem.Web.UI.ExecutorNg.PingByIdResponse> GlobalReportingSystem.Web.UI.ExecutorNg.ExecutorNgSoap.PingByIdAsync(GlobalReportingSystem.Web.UI.ExecutorNg.PingByIdRequest request) {
            return base.Channel.PingByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<GlobalReportingSystem.Web.UI.ExecutorNg.PingByIdResponse> PingByIdAsync(int id) {
            GlobalReportingSystem.Web.UI.ExecutorNg.PingByIdRequest inValue = new GlobalReportingSystem.Web.UI.ExecutorNg.PingByIdRequest();
            inValue.Body = new GlobalReportingSystem.Web.UI.ExecutorNg.PingByIdRequestBody();
            inValue.Body.id = id;
            return ((GlobalReportingSystem.Web.UI.ExecutorNg.ExecutorNgSoap)(this)).PingByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GlobalReportingSystem.Web.UI.ExecutorNg.PingByIpResponse GlobalReportingSystem.Web.UI.ExecutorNg.ExecutorNgSoap.PingByIp(GlobalReportingSystem.Web.UI.ExecutorNg.PingByIpRequest request) {
            return base.Channel.PingByIp(request);
        }
        
        public string PingByIp(string ip) {
            GlobalReportingSystem.Web.UI.ExecutorNg.PingByIpRequest inValue = new GlobalReportingSystem.Web.UI.ExecutorNg.PingByIpRequest();
            inValue.Body = new GlobalReportingSystem.Web.UI.ExecutorNg.PingByIpRequestBody();
            inValue.Body.ip = ip;
            GlobalReportingSystem.Web.UI.ExecutorNg.PingByIpResponse retVal = ((GlobalReportingSystem.Web.UI.ExecutorNg.ExecutorNgSoap)(this)).PingByIp(inValue);
            return retVal.Body.PingByIpResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GlobalReportingSystem.Web.UI.ExecutorNg.PingByIpResponse> GlobalReportingSystem.Web.UI.ExecutorNg.ExecutorNgSoap.PingByIpAsync(GlobalReportingSystem.Web.UI.ExecutorNg.PingByIpRequest request) {
            return base.Channel.PingByIpAsync(request);
        }
        
        public System.Threading.Tasks.Task<GlobalReportingSystem.Web.UI.ExecutorNg.PingByIpResponse> PingByIpAsync(string ip) {
            GlobalReportingSystem.Web.UI.ExecutorNg.PingByIpRequest inValue = new GlobalReportingSystem.Web.UI.ExecutorNg.PingByIpRequest();
            inValue.Body = new GlobalReportingSystem.Web.UI.ExecutorNg.PingByIpRequestBody();
            inValue.Body.ip = ip;
            return ((GlobalReportingSystem.Web.UI.ExecutorNg.ExecutorNgSoap)(this)).PingByIpAsync(inValue);
        }
        
        public void StartLinear(int executionId) {
            base.Channel.StartLinear(executionId);
        }
        
        public System.Threading.Tasks.Task StartLinearAsync(int executionId) {
            return base.Channel.StartLinearAsync(executionId);
        }
        
        public void StartLoadBalanced(int executionId) {
            base.Channel.StartLoadBalanced(executionId);
        }
        
        public System.Threading.Tasks.Task StartLoadBalancedAsync(int executionId) {
            return base.Channel.StartLoadBalancedAsync(executionId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GlobalReportingSystem.Web.UI.ExecutorNg.StopResponse GlobalReportingSystem.Web.UI.ExecutorNg.ExecutorNgSoap.Stop(GlobalReportingSystem.Web.UI.ExecutorNg.StopRequest request) {
            return base.Channel.Stop(request);
        }
        
        public void Stop(string ip) {
            GlobalReportingSystem.Web.UI.ExecutorNg.StopRequest inValue = new GlobalReportingSystem.Web.UI.ExecutorNg.StopRequest();
            inValue.Body = new GlobalReportingSystem.Web.UI.ExecutorNg.StopRequestBody();
            inValue.Body.ip = ip;
            GlobalReportingSystem.Web.UI.ExecutorNg.StopResponse retVal = ((GlobalReportingSystem.Web.UI.ExecutorNg.ExecutorNgSoap)(this)).Stop(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GlobalReportingSystem.Web.UI.ExecutorNg.StopResponse> GlobalReportingSystem.Web.UI.ExecutorNg.ExecutorNgSoap.StopAsync(GlobalReportingSystem.Web.UI.ExecutorNg.StopRequest request) {
            return base.Channel.StopAsync(request);
        }
        
        public System.Threading.Tasks.Task<GlobalReportingSystem.Web.UI.ExecutorNg.StopResponse> StopAsync(string ip) {
            GlobalReportingSystem.Web.UI.ExecutorNg.StopRequest inValue = new GlobalReportingSystem.Web.UI.ExecutorNg.StopRequest();
            inValue.Body = new GlobalReportingSystem.Web.UI.ExecutorNg.StopRequestBody();
            inValue.Body.ip = ip;
            return ((GlobalReportingSystem.Web.UI.ExecutorNg.ExecutorNgSoap)(this)).StopAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GlobalReportingSystem.Web.UI.ExecutorNg.WaitForLinearRelResultsResponse GlobalReportingSystem.Web.UI.ExecutorNg.ExecutorNgSoap.WaitForLinearRelResults(GlobalReportingSystem.Web.UI.ExecutorNg.WaitForLinearRelResultsRequest request) {
            return base.Channel.WaitForLinearRelResults(request);
        }
        
        public string WaitForLinearRelResults(int executionId) {
            GlobalReportingSystem.Web.UI.ExecutorNg.WaitForLinearRelResultsRequest inValue = new GlobalReportingSystem.Web.UI.ExecutorNg.WaitForLinearRelResultsRequest();
            inValue.Body = new GlobalReportingSystem.Web.UI.ExecutorNg.WaitForLinearRelResultsRequestBody();
            inValue.Body.executionId = executionId;
            GlobalReportingSystem.Web.UI.ExecutorNg.WaitForLinearRelResultsResponse retVal = ((GlobalReportingSystem.Web.UI.ExecutorNg.ExecutorNgSoap)(this)).WaitForLinearRelResults(inValue);
            return retVal.Body.WaitForLinearRelResultsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GlobalReportingSystem.Web.UI.ExecutorNg.WaitForLinearRelResultsResponse> GlobalReportingSystem.Web.UI.ExecutorNg.ExecutorNgSoap.WaitForLinearRelResultsAsync(GlobalReportingSystem.Web.UI.ExecutorNg.WaitForLinearRelResultsRequest request) {
            return base.Channel.WaitForLinearRelResultsAsync(request);
        }
        
        public System.Threading.Tasks.Task<GlobalReportingSystem.Web.UI.ExecutorNg.WaitForLinearRelResultsResponse> WaitForLinearRelResultsAsync(int executionId) {
            GlobalReportingSystem.Web.UI.ExecutorNg.WaitForLinearRelResultsRequest inValue = new GlobalReportingSystem.Web.UI.ExecutorNg.WaitForLinearRelResultsRequest();
            inValue.Body = new GlobalReportingSystem.Web.UI.ExecutorNg.WaitForLinearRelResultsRequestBody();
            inValue.Body.executionId = executionId;
            return ((GlobalReportingSystem.Web.UI.ExecutorNg.ExecutorNgSoap)(this)).WaitForLinearRelResultsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GlobalReportingSystem.Web.UI.ExecutorNg.WaitForLbRelResultsResponse GlobalReportingSystem.Web.UI.ExecutorNg.ExecutorNgSoap.WaitForLbRelResults(GlobalReportingSystem.Web.UI.ExecutorNg.WaitForLbRelResultsRequest request) {
            return base.Channel.WaitForLbRelResults(request);
        }
        
        public string WaitForLbRelResults(int executionId) {
            GlobalReportingSystem.Web.UI.ExecutorNg.WaitForLbRelResultsRequest inValue = new GlobalReportingSystem.Web.UI.ExecutorNg.WaitForLbRelResultsRequest();
            inValue.Body = new GlobalReportingSystem.Web.UI.ExecutorNg.WaitForLbRelResultsRequestBody();
            inValue.Body.executionId = executionId;
            GlobalReportingSystem.Web.UI.ExecutorNg.WaitForLbRelResultsResponse retVal = ((GlobalReportingSystem.Web.UI.ExecutorNg.ExecutorNgSoap)(this)).WaitForLbRelResults(inValue);
            return retVal.Body.WaitForLbRelResultsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GlobalReportingSystem.Web.UI.ExecutorNg.WaitForLbRelResultsResponse> GlobalReportingSystem.Web.UI.ExecutorNg.ExecutorNgSoap.WaitForLbRelResultsAsync(GlobalReportingSystem.Web.UI.ExecutorNg.WaitForLbRelResultsRequest request) {
            return base.Channel.WaitForLbRelResultsAsync(request);
        }
        
        public System.Threading.Tasks.Task<GlobalReportingSystem.Web.UI.ExecutorNg.WaitForLbRelResultsResponse> WaitForLbRelResultsAsync(int executionId) {
            GlobalReportingSystem.Web.UI.ExecutorNg.WaitForLbRelResultsRequest inValue = new GlobalReportingSystem.Web.UI.ExecutorNg.WaitForLbRelResultsRequest();
            inValue.Body = new GlobalReportingSystem.Web.UI.ExecutorNg.WaitForLbRelResultsRequestBody();
            inValue.Body.executionId = executionId;
            return ((GlobalReportingSystem.Web.UI.ExecutorNg.ExecutorNgSoap)(this)).WaitForLbRelResultsAsync(inValue);
        }
    }
}
